/**
 * Seeder para Catálogo CIE-10
 * Códigos de la Clasificación Internacional de Enfermedades 10ª Revisión
 *
 * Ejecutar con: node seeders/cie10.seeder.js
 */

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// Códigos CIE-10 más comunes organizados por capítulo
const CIE10_CODIGOS = [
  // CAPÍTULO I: Enfermedades infecciosas y parasitarias (A00-B99)
  { codigo: 'A00', descripcion: 'Cólera', capitulo: 'I', grupo: 'A00-A09' },
  { codigo: 'A01', descripcion: 'Fiebres tifoidea y paratifoidea', capitulo: 'I', grupo: 'A00-A09' },
  { codigo: 'A02', descripcion: 'Otras infecciones por Salmonella', capitulo: 'I', grupo: 'A00-A09' },
  { codigo: 'A03', descripcion: 'Shigelosis', capitulo: 'I', grupo: 'A00-A09' },
  { codigo: 'A04', descripcion: 'Otras infecciones intestinales bacterianas', capitulo: 'I', grupo: 'A00-A09' },
  { codigo: 'A05', descripcion: 'Otras intoxicaciones alimentarias bacterianas', capitulo: 'I', grupo: 'A00-A09' },
  { codigo: 'A06', descripcion: 'Amebiasis', capitulo: 'I', grupo: 'A00-A09' },
  { codigo: 'A07', descripcion: 'Otras enfermedades intestinales por protozoarios', capitulo: 'I', grupo: 'A00-A09' },
  { codigo: 'A08', descripcion: 'Infecciones intestinales debidas a virus', capitulo: 'I', grupo: 'A00-A09' },
  { codigo: 'A09', descripcion: 'Diarrea y gastroenteritis de origen infeccioso', capitulo: 'I', grupo: 'A00-A09' },
  { codigo: 'A15', descripcion: 'Tuberculosis respiratoria, confirmada bacteriológica e histológicamente', capitulo: 'I', grupo: 'A15-A19' },
  { codigo: 'A16', descripcion: 'Tuberculosis respiratoria, no confirmada bacteriológica o histológicamente', capitulo: 'I', grupo: 'A15-A19' },
  { codigo: 'A37', descripcion: 'Tos ferina', capitulo: 'I', grupo: 'A30-A49' },
  { codigo: 'A38', descripcion: 'Escarlatina', capitulo: 'I', grupo: 'A30-A49' },
  { codigo: 'A39', descripcion: 'Infección meningocócica', capitulo: 'I', grupo: 'A30-A49' },
  { codigo: 'A40', descripcion: 'Septicemia estreptocócica', capitulo: 'I', grupo: 'A30-A49' },
  { codigo: 'A41', descripcion: 'Otras septicemias', capitulo: 'I', grupo: 'A30-A49' },
  { codigo: 'A46', descripcion: 'Erisipela', capitulo: 'I', grupo: 'A30-A49' },
  { codigo: 'A49', descripcion: 'Infección bacteriana, sitio no especificado', capitulo: 'I', grupo: 'A30-A49' },
  { codigo: 'B01', descripcion: 'Varicela', capitulo: 'I', grupo: 'B00-B09' },
  { codigo: 'B02', descripcion: 'Herpes zóster', capitulo: 'I', grupo: 'B00-B09' },
  { codigo: 'B05', descripcion: 'Sarampión', capitulo: 'I', grupo: 'B00-B09' },
  { codigo: 'B06', descripcion: 'Rubéola', capitulo: 'I', grupo: 'B00-B09' },
  { codigo: 'B15', descripcion: 'Hepatitis aguda tipo A', capitulo: 'I', grupo: 'B15-B19' },
  { codigo: 'B16', descripcion: 'Hepatitis aguda tipo B', capitulo: 'I', grupo: 'B15-B19' },
  { codigo: 'B17', descripcion: 'Otras hepatitis virales agudas', capitulo: 'I', grupo: 'B15-B19' },
  { codigo: 'B18', descripcion: 'Hepatitis viral crónica', capitulo: 'I', grupo: 'B15-B19' },
  { codigo: 'B19', descripcion: 'Hepatitis viral, sin otra especificación', capitulo: 'I', grupo: 'B15-B19' },
  { codigo: 'B20', descripcion: 'Enfermedad por VIH, resultante en enfermedades infecciosas', capitulo: 'I', grupo: 'B20-B24' },
  { codigo: 'B24', descripcion: 'Enfermedad por VIH, sin otra especificación', capitulo: 'I', grupo: 'B20-B24' },
  { codigo: 'B34', descripcion: 'Infección viral, sitio no especificado', capitulo: 'I', grupo: 'B25-B34' },
  { codigo: 'B37', descripcion: 'Candidiasis', capitulo: 'I', grupo: 'B35-B49' },

  // CAPÍTULO II: Neoplasias (C00-D48)
  { codigo: 'C16', descripcion: 'Tumor maligno del estómago', capitulo: 'II', grupo: 'C15-C26' },
  { codigo: 'C18', descripcion: 'Tumor maligno del colon', capitulo: 'II', grupo: 'C15-C26' },
  { codigo: 'C20', descripcion: 'Tumor maligno del recto', capitulo: 'II', grupo: 'C15-C26' },
  { codigo: 'C34', descripcion: 'Tumor maligno del bronquio y del pulmón', capitulo: 'II', grupo: 'C30-C39' },
  { codigo: 'C50', descripcion: 'Tumor maligno de la mama', capitulo: 'II', grupo: 'C50' },
  { codigo: 'C53', descripcion: 'Tumor maligno del cuello del útero', capitulo: 'II', grupo: 'C51-C58' },
  { codigo: 'C54', descripcion: 'Tumor maligno del cuerpo del útero', capitulo: 'II', grupo: 'C51-C58' },
  { codigo: 'C56', descripcion: 'Tumor maligno del ovario', capitulo: 'II', grupo: 'C51-C58' },
  { codigo: 'C61', descripcion: 'Tumor maligno de la próstata', capitulo: 'II', grupo: 'C60-C63' },
  { codigo: 'C67', descripcion: 'Tumor maligno de la vejiga urinaria', capitulo: 'II', grupo: 'C64-C68' },
  { codigo: 'C73', descripcion: 'Tumor maligno de la glándula tiroides', capitulo: 'II', grupo: 'C73-C75' },
  { codigo: 'C91', descripcion: 'Leucemia linfoide', capitulo: 'II', grupo: 'C81-C96' },
  { codigo: 'C92', descripcion: 'Leucemia mieloide', capitulo: 'II', grupo: 'C81-C96' },
  { codigo: 'D25', descripcion: 'Leiomioma del útero', capitulo: 'II', grupo: 'D10-D36' },

  // CAPÍTULO III: Enfermedades de la sangre (D50-D89)
  { codigo: 'D50', descripcion: 'Anemia por deficiencia de hierro', capitulo: 'III', grupo: 'D50-D53' },
  { codigo: 'D51', descripcion: 'Anemia por deficiencia de vitamina B12', capitulo: 'III', grupo: 'D50-D53' },
  { codigo: 'D52', descripcion: 'Anemia por deficiencia de folatos', capitulo: 'III', grupo: 'D50-D53' },
  { codigo: 'D56', descripcion: 'Talasemia', capitulo: 'III', grupo: 'D55-D59' },
  { codigo: 'D57', descripcion: 'Trastornos drepanocíticos', capitulo: 'III', grupo: 'D55-D59' },
  { codigo: 'D64', descripcion: 'Otras anemias', capitulo: 'III', grupo: 'D60-D64' },
  { codigo: 'D69', descripcion: 'Púrpura y otras afecciones hemorrágicas', capitulo: 'III', grupo: 'D65-D69' },

  // CAPÍTULO IV: Enfermedades endocrinas (E00-E90)
  { codigo: 'E03', descripcion: 'Otros hipotiroidismos', capitulo: 'IV', grupo: 'E00-E07' },
  { codigo: 'E04', descripcion: 'Otros bocios no tóxicos', capitulo: 'IV', grupo: 'E00-E07' },
  { codigo: 'E05', descripcion: 'Tirotoxicosis [hipertiroidismo]', capitulo: 'IV', grupo: 'E00-E07' },
  { codigo: 'E10', descripcion: 'Diabetes mellitus insulinodependiente', capitulo: 'IV', grupo: 'E10-E14' },
  { codigo: 'E11', descripcion: 'Diabetes mellitus no insulinodependiente', capitulo: 'IV', grupo: 'E10-E14' },
  { codigo: 'E14', descripcion: 'Diabetes mellitus, no especificada', capitulo: 'IV', grupo: 'E10-E14' },
  { codigo: 'E16', descripcion: 'Otros trastornos de la secreción interna del páncreas', capitulo: 'IV', grupo: 'E15-E16' },
  { codigo: 'E20', descripcion: 'Hipoparatiroidismo', capitulo: 'IV', grupo: 'E20-E35' },
  { codigo: 'E21', descripcion: 'Hiperparatiroidismo y otros trastornos de la paratiroides', capitulo: 'IV', grupo: 'E20-E35' },
  { codigo: 'E23', descripcion: 'Hipofunción y otros trastornos de la hipófisis', capitulo: 'IV', grupo: 'E20-E35' },
  { codigo: 'E27', descripcion: 'Otros trastornos de la glándula suprarrenal', capitulo: 'IV', grupo: 'E20-E35' },
  { codigo: 'E28', descripcion: 'Disfunción ovárica', capitulo: 'IV', grupo: 'E20-E35' },
  { codigo: 'E29', descripcion: 'Disfunción testicular', capitulo: 'IV', grupo: 'E20-E35' },
  { codigo: 'E34', descripcion: 'Otros trastornos endocrinos', capitulo: 'IV', grupo: 'E20-E35' },
  { codigo: 'E66', descripcion: 'Obesidad', capitulo: 'IV', grupo: 'E65-E68' },
  { codigo: 'E78', descripcion: 'Trastornos del metabolismo de las lipoproteínas', capitulo: 'IV', grupo: 'E70-E90' },
  { codigo: 'E79', descripcion: 'Trastornos del metabolismo de las purinas y pirimidinas', capitulo: 'IV', grupo: 'E70-E90' },
  { codigo: 'E83', descripcion: 'Trastornos del metabolismo de los minerales', capitulo: 'IV', grupo: 'E70-E90' },
  { codigo: 'E86', descripcion: 'Depleción del volumen', capitulo: 'IV', grupo: 'E70-E90' },
  { codigo: 'E87', descripcion: 'Otros trastornos de líquidos, electrolitos y equilibrio ácido-base', capitulo: 'IV', grupo: 'E70-E90' },

  // CAPÍTULO V: Trastornos mentales (F00-F99)
  { codigo: 'F00', descripcion: 'Demencia en la enfermedad de Alzheimer', capitulo: 'V', grupo: 'F00-F09' },
  { codigo: 'F01', descripcion: 'Demencia vascular', capitulo: 'V', grupo: 'F00-F09' },
  { codigo: 'F03', descripcion: 'Demencia, no especificada', capitulo: 'V', grupo: 'F00-F09' },
  { codigo: 'F10', descripcion: 'Trastornos mentales por uso de alcohol', capitulo: 'V', grupo: 'F10-F19' },
  { codigo: 'F11', descripcion: 'Trastornos mentales por uso de opiáceos', capitulo: 'V', grupo: 'F10-F19' },
  { codigo: 'F12', descripcion: 'Trastornos mentales por uso de cannabinoides', capitulo: 'V', grupo: 'F10-F19' },
  { codigo: 'F17', descripcion: 'Trastornos mentales por uso de tabaco', capitulo: 'V', grupo: 'F10-F19' },
  { codigo: 'F19', descripcion: 'Trastornos mentales por uso de múltiples drogas', capitulo: 'V', grupo: 'F10-F19' },
  { codigo: 'F20', descripcion: 'Esquizofrenia', capitulo: 'V', grupo: 'F20-F29' },
  { codigo: 'F30', descripcion: 'Episodio maníaco', capitulo: 'V', grupo: 'F30-F39' },
  { codigo: 'F31', descripcion: 'Trastorno afectivo bipolar', capitulo: 'V', grupo: 'F30-F39' },
  { codigo: 'F32', descripcion: 'Episodio depresivo', capitulo: 'V', grupo: 'F30-F39' },
  { codigo: 'F33', descripcion: 'Trastorno depresivo recurrente', capitulo: 'V', grupo: 'F30-F39' },
  { codigo: 'F40', descripcion: 'Trastornos fóbicos de ansiedad', capitulo: 'V', grupo: 'F40-F48' },
  { codigo: 'F41', descripcion: 'Otros trastornos de ansiedad', capitulo: 'V', grupo: 'F40-F48' },
  { codigo: 'F43', descripcion: 'Reacción al estrés grave y trastornos de adaptación', capitulo: 'V', grupo: 'F40-F48' },
  { codigo: 'F45', descripcion: 'Trastornos somatomorfos', capitulo: 'V', grupo: 'F40-F48' },
  { codigo: 'F50', descripcion: 'Trastornos de la ingestión de alimentos', capitulo: 'V', grupo: 'F50-F59' },
  { codigo: 'F51', descripcion: 'Trastornos no orgánicos del sueño', capitulo: 'V', grupo: 'F50-F59' },
  { codigo: 'F84', descripcion: 'Trastornos generalizados del desarrollo', capitulo: 'V', grupo: 'F80-F89' },
  { codigo: 'F90', descripcion: 'Trastornos hipercinéticos', capitulo: 'V', grupo: 'F90-F98' },

  // CAPÍTULO VI: Enfermedades del sistema nervioso (G00-G99)
  { codigo: 'G00', descripcion: 'Meningitis bacteriana, no clasificada en otra parte', capitulo: 'VI', grupo: 'G00-G09' },
  { codigo: 'G03', descripcion: 'Meningitis por otras causas', capitulo: 'VI', grupo: 'G00-G09' },
  { codigo: 'G20', descripcion: 'Enfermedad de Parkinson', capitulo: 'VI', grupo: 'G20-G26' },
  { codigo: 'G25', descripcion: 'Otros trastornos extrapiramidales y del movimiento', capitulo: 'VI', grupo: 'G20-G26' },
  { codigo: 'G30', descripcion: 'Enfermedad de Alzheimer', capitulo: 'VI', grupo: 'G30-G32' },
  { codigo: 'G35', descripcion: 'Esclerosis múltiple', capitulo: 'VI', grupo: 'G35-G37' },
  { codigo: 'G40', descripcion: 'Epilepsia', capitulo: 'VI', grupo: 'G40-G47' },
  { codigo: 'G43', descripcion: 'Migraña', capitulo: 'VI', grupo: 'G40-G47' },
  { codigo: 'G44', descripcion: 'Otros síndromes de cefalea', capitulo: 'VI', grupo: 'G40-G47' },
  { codigo: 'G45', descripcion: 'Ataques de isquemia cerebral transitoria', capitulo: 'VI', grupo: 'G40-G47' },
  { codigo: 'G47', descripcion: 'Trastornos del sueño', capitulo: 'VI', grupo: 'G40-G47' },
  { codigo: 'G50', descripcion: 'Trastornos del nervio trigémino', capitulo: 'VI', grupo: 'G50-G59' },
  { codigo: 'G51', descripcion: 'Trastornos del nervio facial', capitulo: 'VI', grupo: 'G50-G59' },
  { codigo: 'G56', descripcion: 'Mononeuropatía del miembro superior', capitulo: 'VI', grupo: 'G50-G59' },
  { codigo: 'G57', descripcion: 'Mononeuropatía del miembro inferior', capitulo: 'VI', grupo: 'G50-G59' },
  { codigo: 'G62', descripcion: 'Otras polineuropatías', capitulo: 'VI', grupo: 'G60-G64' },

  // CAPÍTULO VII: Enfermedades del ojo (H00-H59)
  { codigo: 'H00', descripcion: 'Orzuelo y calacio', capitulo: 'VII', grupo: 'H00-H06' },
  { codigo: 'H01', descripcion: 'Otras inflamaciones del párpado', capitulo: 'VII', grupo: 'H00-H06' },
  { codigo: 'H10', descripcion: 'Conjuntivitis', capitulo: 'VII', grupo: 'H10-H13' },
  { codigo: 'H11', descripcion: 'Otros trastornos de la conjuntiva', capitulo: 'VII', grupo: 'H10-H13' },
  { codigo: 'H16', descripcion: 'Queratitis', capitulo: 'VII', grupo: 'H15-H22' },
  { codigo: 'H25', descripcion: 'Catarata senil', capitulo: 'VII', grupo: 'H25-H28' },
  { codigo: 'H26', descripcion: 'Otras cataratas', capitulo: 'VII', grupo: 'H25-H28' },
  { codigo: 'H35', descripcion: 'Otros trastornos de la retina', capitulo: 'VII', grupo: 'H30-H36' },
  { codigo: 'H36', descripcion: 'Trastornos de la retina en enfermedades clasificadas en otra parte', capitulo: 'VII', grupo: 'H30-H36' },
  { codigo: 'H40', descripcion: 'Glaucoma', capitulo: 'VII', grupo: 'H40-H42' },
  { codigo: 'H52', descripcion: 'Trastornos de la acomodación y de la refracción', capitulo: 'VII', grupo: 'H49-H52' },
  { codigo: 'H53', descripcion: 'Perturbaciones de la visión', capitulo: 'VII', grupo: 'H53-H54' },
  { codigo: 'H54', descripcion: 'Ceguera y disminución de la agudeza visual', capitulo: 'VII', grupo: 'H53-H54' },

  // CAPÍTULO VIII: Enfermedades del oído (H60-H95)
  { codigo: 'H60', descripcion: 'Otitis externa', capitulo: 'VIII', grupo: 'H60-H62' },
  { codigo: 'H65', descripcion: 'Otitis media no supurativa', capitulo: 'VIII', grupo: 'H65-H75' },
  { codigo: 'H66', descripcion: 'Otitis media supurativa y no especificada', capitulo: 'VIII', grupo: 'H65-H75' },
  { codigo: 'H70', descripcion: 'Mastoiditis y afecciones relacionadas', capitulo: 'VIII', grupo: 'H65-H75' },
  { codigo: 'H81', descripcion: 'Trastornos de la función vestibular', capitulo: 'VIII', grupo: 'H80-H83' },
  { codigo: 'H83', descripcion: 'Otros trastornos del oído interno', capitulo: 'VIII', grupo: 'H80-H83' },
  { codigo: 'H90', descripcion: 'Hipoacusia conductiva y neurosensorial', capitulo: 'VIII', grupo: 'H90-H95' },
  { codigo: 'H91', descripcion: 'Otra hipoacusia', capitulo: 'VIII', grupo: 'H90-H95' },

  // CAPÍTULO IX: Enfermedades del sistema circulatorio (I00-I99)
  { codigo: 'I00', descripcion: 'Fiebre reumática sin mención de complicación cardíaca', capitulo: 'IX', grupo: 'I00-I02' },
  { codigo: 'I10', descripcion: 'Hipertensión esencial (primaria)', capitulo: 'IX', grupo: 'I10-I15' },
  { codigo: 'I11', descripcion: 'Enfermedad cardíaca hipertensiva', capitulo: 'IX', grupo: 'I10-I15' },
  { codigo: 'I12', descripcion: 'Enfermedad renal hipertensiva', capitulo: 'IX', grupo: 'I10-I15' },
  { codigo: 'I13', descripcion: 'Enfermedad cardíaca y renal hipertensiva', capitulo: 'IX', grupo: 'I10-I15' },
  { codigo: 'I15', descripcion: 'Hipertensión secundaria', capitulo: 'IX', grupo: 'I10-I15' },
  { codigo: 'I20', descripcion: 'Angina de pecho', capitulo: 'IX', grupo: 'I20-I25' },
  { codigo: 'I21', descripcion: 'Infarto agudo del miocardio', capitulo: 'IX', grupo: 'I20-I25' },
  { codigo: 'I22', descripcion: 'Infarto subsiguiente del miocardio', capitulo: 'IX', grupo: 'I20-I25' },
  { codigo: 'I25', descripcion: 'Enfermedad isquémica crónica del corazón', capitulo: 'IX', grupo: 'I20-I25' },
  { codigo: 'I26', descripcion: 'Embolia pulmonar', capitulo: 'IX', grupo: 'I26-I28' },
  { codigo: 'I30', descripcion: 'Pericarditis aguda', capitulo: 'IX', grupo: 'I30-I52' },
  { codigo: 'I34', descripcion: 'Trastornos no reumáticos de la válvula mitral', capitulo: 'IX', grupo: 'I30-I52' },
  { codigo: 'I35', descripcion: 'Trastornos no reumáticos de la válvula aórtica', capitulo: 'IX', grupo: 'I30-I52' },
  { codigo: 'I42', descripcion: 'Cardiomiopatía', capitulo: 'IX', grupo: 'I30-I52' },
  { codigo: 'I44', descripcion: 'Bloqueo auriculoventricular y de rama izquierda del haz', capitulo: 'IX', grupo: 'I30-I52' },
  { codigo: 'I47', descripcion: 'Taquicardia paroxística', capitulo: 'IX', grupo: 'I30-I52' },
  { codigo: 'I48', descripcion: 'Fibrilación y aleteo auricular', capitulo: 'IX', grupo: 'I30-I52' },
  { codigo: 'I49', descripcion: 'Otras arritmias cardíacas', capitulo: 'IX', grupo: 'I30-I52' },
  { codigo: 'I50', descripcion: 'Insuficiencia cardíaca', capitulo: 'IX', grupo: 'I30-I52' },
  { codigo: 'I60', descripcion: 'Hemorragia subaracnoidea', capitulo: 'IX', grupo: 'I60-I69' },
  { codigo: 'I61', descripcion: 'Hemorragia intracerebral', capitulo: 'IX', grupo: 'I60-I69' },
  { codigo: 'I63', descripcion: 'Infarto cerebral', capitulo: 'IX', grupo: 'I60-I69' },
  { codigo: 'I64', descripcion: 'Accidente vascular encefálico, no especificado', capitulo: 'IX', grupo: 'I60-I69' },
  { codigo: 'I67', descripcion: 'Otras enfermedades cerebrovasculares', capitulo: 'IX', grupo: 'I60-I69' },
  { codigo: 'I70', descripcion: 'Aterosclerosis', capitulo: 'IX', grupo: 'I70-I79' },
  { codigo: 'I73', descripcion: 'Otras enfermedades vasculares periféricas', capitulo: 'IX', grupo: 'I70-I79' },
  { codigo: 'I74', descripcion: 'Embolia y trombosis arteriales', capitulo: 'IX', grupo: 'I70-I79' },
  { codigo: 'I80', descripcion: 'Flebitis y tromboflebitis', capitulo: 'IX', grupo: 'I80-I89' },
  { codigo: 'I83', descripcion: 'Venas varicosas de los miembros inferiores', capitulo: 'IX', grupo: 'I80-I89' },
  { codigo: 'I84', descripcion: 'Hemorroides', capitulo: 'IX', grupo: 'I80-I89' },
  { codigo: 'I87', descripcion: 'Otros trastornos de las venas', capitulo: 'IX', grupo: 'I80-I89' },
  { codigo: 'I95', descripcion: 'Hipotensión', capitulo: 'IX', grupo: 'I95-I99' },

  // CAPÍTULO X: Enfermedades del sistema respiratorio (J00-J99)
  { codigo: 'J00', descripcion: 'Rinofaringitis aguda [resfriado común]', capitulo: 'X', grupo: 'J00-J06' },
  { codigo: 'J01', descripcion: 'Sinusitis aguda', capitulo: 'X', grupo: 'J00-J06' },
  { codigo: 'J02', descripcion: 'Faringitis aguda', capitulo: 'X', grupo: 'J00-J06' },
  { codigo: 'J03', descripcion: 'Amigdalitis aguda', capitulo: 'X', grupo: 'J00-J06' },
  { codigo: 'J04', descripcion: 'Laringitis y traqueítis agudas', capitulo: 'X', grupo: 'J00-J06' },
  { codigo: 'J06', descripcion: 'Infecciones agudas de las vías respiratorias superiores', capitulo: 'X', grupo: 'J00-J06' },
  { codigo: 'J10', descripcion: 'Influenza debida a virus de la influenza identificado', capitulo: 'X', grupo: 'J09-J18' },
  { codigo: 'J11', descripcion: 'Influenza, virus no identificado', capitulo: 'X', grupo: 'J09-J18' },
  { codigo: 'J12', descripcion: 'Neumonía viral, no clasificada en otra parte', capitulo: 'X', grupo: 'J09-J18' },
  { codigo: 'J13', descripcion: 'Neumonía debida a Streptococcus pneumoniae', capitulo: 'X', grupo: 'J09-J18' },
  { codigo: 'J14', descripcion: 'Neumonía debida a Haemophilus influenzae', capitulo: 'X', grupo: 'J09-J18' },
  { codigo: 'J15', descripcion: 'Neumonía bacteriana, no clasificada en otra parte', capitulo: 'X', grupo: 'J09-J18' },
  { codigo: 'J18', descripcion: 'Neumonía, organismo no especificado', capitulo: 'X', grupo: 'J09-J18' },
  { codigo: 'J20', descripcion: 'Bronquitis aguda', capitulo: 'X', grupo: 'J20-J22' },
  { codigo: 'J21', descripcion: 'Bronquiolitis aguda', capitulo: 'X', grupo: 'J20-J22' },
  { codigo: 'J22', descripcion: 'Infección aguda no especificada de las vías respiratorias inferiores', capitulo: 'X', grupo: 'J20-J22' },
  { codigo: 'J30', descripcion: 'Rinitis alérgica y vasomotora', capitulo: 'X', grupo: 'J30-J39' },
  { codigo: 'J31', descripcion: 'Rinitis, nasofaringitis y faringitis crónicas', capitulo: 'X', grupo: 'J30-J39' },
  { codigo: 'J32', descripcion: 'Sinusitis crónica', capitulo: 'X', grupo: 'J30-J39' },
  { codigo: 'J34', descripcion: 'Otros trastornos de la nariz y de los senos paranasales', capitulo: 'X', grupo: 'J30-J39' },
  { codigo: 'J35', descripcion: 'Enfermedades crónicas de las amígdalas y adenoides', capitulo: 'X', grupo: 'J30-J39' },
  { codigo: 'J37', descripcion: 'Laringitis y laringotraqueítis crónicas', capitulo: 'X', grupo: 'J30-J39' },
  { codigo: 'J40', descripcion: 'Bronquitis, no especificada como aguda o crónica', capitulo: 'X', grupo: 'J40-J47' },
  { codigo: 'J41', descripcion: 'Bronquitis crónica simple y mucopurulenta', capitulo: 'X', grupo: 'J40-J47' },
  { codigo: 'J42', descripcion: 'Bronquitis crónica no especificada', capitulo: 'X', grupo: 'J40-J47' },
  { codigo: 'J43', descripcion: 'Enfisema', capitulo: 'X', grupo: 'J40-J47' },
  { codigo: 'J44', descripcion: 'Otras enfermedades pulmonares obstructivas crónicas', capitulo: 'X', grupo: 'J40-J47' },
  { codigo: 'J45', descripcion: 'Asma', capitulo: 'X', grupo: 'J40-J47' },
  { codigo: 'J46', descripcion: 'Estado asmático', capitulo: 'X', grupo: 'J40-J47' },
  { codigo: 'J47', descripcion: 'Bronquiectasia', capitulo: 'X', grupo: 'J40-J47' },
  { codigo: 'J81', descripcion: 'Edema pulmonar', capitulo: 'X', grupo: 'J80-J84' },
  { codigo: 'J84', descripcion: 'Otras enfermedades pulmonares intersticiales', capitulo: 'X', grupo: 'J80-J84' },
  { codigo: 'J90', descripcion: 'Derrame pleural, no clasificado en otra parte', capitulo: 'X', grupo: 'J90-J94' },
  { codigo: 'J93', descripcion: 'Neumotórax', capitulo: 'X', grupo: 'J90-J94' },
  { codigo: 'J96', descripcion: 'Insuficiencia respiratoria, no clasificada en otra parte', capitulo: 'X', grupo: 'J95-J99' },
  { codigo: 'J98', descripcion: 'Otros trastornos respiratorios', capitulo: 'X', grupo: 'J95-J99' },

  // CAPÍTULO XI: Enfermedades del sistema digestivo (K00-K93)
  { codigo: 'K00', descripcion: 'Trastornos del desarrollo y de la erupción de los dientes', capitulo: 'XI', grupo: 'K00-K14' },
  { codigo: 'K01', descripcion: 'Dientes incluidos e impactados', capitulo: 'XI', grupo: 'K00-K14' },
  { codigo: 'K02', descripcion: 'Caries dental', capitulo: 'XI', grupo: 'K00-K14' },
  { codigo: 'K04', descripcion: 'Enfermedades de la pulpa y de los tejidos periapicales', capitulo: 'XI', grupo: 'K00-K14' },
  { codigo: 'K05', descripcion: 'Gingivitis y enfermedades periodontales', capitulo: 'XI', grupo: 'K00-K14' },
  { codigo: 'K08', descripcion: 'Otros trastornos de los dientes y de sus estructuras de sostén', capitulo: 'XI', grupo: 'K00-K14' },
  { codigo: 'K20', descripcion: 'Esofagitis', capitulo: 'XI', grupo: 'K20-K31' },
  { codigo: 'K21', descripcion: 'Enfermedad del reflujo gastroesofágico', capitulo: 'XI', grupo: 'K20-K31' },
  { codigo: 'K25', descripcion: 'Úlcera gástrica', capitulo: 'XI', grupo: 'K20-K31' },
  { codigo: 'K26', descripcion: 'Úlcera duodenal', capitulo: 'XI', grupo: 'K20-K31' },
  { codigo: 'K27', descripcion: 'Úlcera péptica, de sitio no especificado', capitulo: 'XI', grupo: 'K20-K31' },
  { codigo: 'K29', descripcion: 'Gastritis y duodenitis', capitulo: 'XI', grupo: 'K20-K31' },
  { codigo: 'K30', descripcion: 'Dispepsia', capitulo: 'XI', grupo: 'K20-K31' },
  { codigo: 'K35', descripcion: 'Apendicitis aguda', capitulo: 'XI', grupo: 'K35-K38' },
  { codigo: 'K37', descripcion: 'Apendicitis, no especificada', capitulo: 'XI', grupo: 'K35-K38' },
  { codigo: 'K40', descripcion: 'Hernia inguinal', capitulo: 'XI', grupo: 'K40-K46' },
  { codigo: 'K41', descripcion: 'Hernia femoral', capitulo: 'XI', grupo: 'K40-K46' },
  { codigo: 'K42', descripcion: 'Hernia umbilical', capitulo: 'XI', grupo: 'K40-K46' },
  { codigo: 'K43', descripcion: 'Hernia ventral', capitulo: 'XI', grupo: 'K40-K46' },
  { codigo: 'K44', descripcion: 'Hernia diafragmática', capitulo: 'XI', grupo: 'K40-K46' },
  { codigo: 'K50', descripcion: 'Enfermedad de Crohn [enteritis regional]', capitulo: 'XI', grupo: 'K50-K52' },
  { codigo: 'K51', descripcion: 'Colitis ulcerativa', capitulo: 'XI', grupo: 'K50-K52' },
  { codigo: 'K52', descripcion: 'Otras gastroenteritis y colitis no infecciosas', capitulo: 'XI', grupo: 'K50-K52' },
  { codigo: 'K55', descripcion: 'Trastornos vasculares del intestino', capitulo: 'XI', grupo: 'K55-K63' },
  { codigo: 'K56', descripcion: 'Íleo paralítico y obstrucción intestinal sin hernia', capitulo: 'XI', grupo: 'K55-K63' },
  { codigo: 'K57', descripcion: 'Enfermedad diverticular del intestino', capitulo: 'XI', grupo: 'K55-K63' },
  { codigo: 'K58', descripcion: 'Síndrome del colon irritable', capitulo: 'XI', grupo: 'K55-K63' },
  { codigo: 'K59', descripcion: 'Otros trastornos funcionales del intestino', capitulo: 'XI', grupo: 'K55-K63' },
  { codigo: 'K60', descripcion: 'Fisura y fístula de las regiones anal y rectal', capitulo: 'XI', grupo: 'K55-K63' },
  { codigo: 'K61', descripcion: 'Absceso de las regiones anal y rectal', capitulo: 'XI', grupo: 'K55-K63' },
  { codigo: 'K62', descripcion: 'Otras enfermedades del ano y del recto', capitulo: 'XI', grupo: 'K55-K63' },
  { codigo: 'K63', descripcion: 'Otras enfermedades del intestino', capitulo: 'XI', grupo: 'K55-K63' },
  { codigo: 'K65', descripcion: 'Peritonitis', capitulo: 'XI', grupo: 'K65-K67' },
  { codigo: 'K70', descripcion: 'Enfermedad alcohólica del hígado', capitulo: 'XI', grupo: 'K70-K77' },
  { codigo: 'K71', descripcion: 'Enfermedad tóxica del hígado', capitulo: 'XI', grupo: 'K70-K77' },
  { codigo: 'K72', descripcion: 'Insuficiencia hepática, no clasificada en otra parte', capitulo: 'XI', grupo: 'K70-K77' },
  { codigo: 'K73', descripcion: 'Hepatitis crónica, no clasificada en otra parte', capitulo: 'XI', grupo: 'K70-K77' },
  { codigo: 'K74', descripcion: 'Fibrosis y cirrosis del hígado', capitulo: 'XI', grupo: 'K70-K77' },
  { codigo: 'K75', descripcion: 'Otras enfermedades inflamatorias del hígado', capitulo: 'XI', grupo: 'K70-K77' },
  { codigo: 'K76', descripcion: 'Otras enfermedades del hígado', capitulo: 'XI', grupo: 'K70-K77' },
  { codigo: 'K80', descripcion: 'Colelitiasis', capitulo: 'XI', grupo: 'K80-K87' },
  { codigo: 'K81', descripcion: 'Colecistitis', capitulo: 'XI', grupo: 'K80-K87' },
  { codigo: 'K82', descripcion: 'Otras enfermedades de la vesícula biliar', capitulo: 'XI', grupo: 'K80-K87' },
  { codigo: 'K83', descripcion: 'Otras enfermedades de las vías biliares', capitulo: 'XI', grupo: 'K80-K87' },
  { codigo: 'K85', descripcion: 'Pancreatitis aguda', capitulo: 'XI', grupo: 'K80-K87' },
  { codigo: 'K86', descripcion: 'Otras enfermedades del páncreas', capitulo: 'XI', grupo: 'K80-K87' },
  { codigo: 'K92', descripcion: 'Otras enfermedades del sistema digestivo', capitulo: 'XI', grupo: 'K90-K93' },

  // CAPÍTULO XII: Enfermedades de la piel (L00-L99)
  { codigo: 'L00', descripcion: 'Síndrome estafilocócico de la piel escaldada', capitulo: 'XII', grupo: 'L00-L08' },
  { codigo: 'L01', descripcion: 'Impétigo', capitulo: 'XII', grupo: 'L00-L08' },
  { codigo: 'L02', descripcion: 'Absceso cutáneo, furúnculo y carbunco', capitulo: 'XII', grupo: 'L00-L08' },
  { codigo: 'L03', descripcion: 'Celulitis', capitulo: 'XII', grupo: 'L00-L08' },
  { codigo: 'L04', descripcion: 'Linfadenitis aguda', capitulo: 'XII', grupo: 'L00-L08' },
  { codigo: 'L08', descripcion: 'Otras infecciones locales de la piel y del tejido subcutáneo', capitulo: 'XII', grupo: 'L00-L08' },
  { codigo: 'L20', descripcion: 'Dermatitis atópica', capitulo: 'XII', grupo: 'L20-L30' },
  { codigo: 'L21', descripcion: 'Dermatitis seborreica', capitulo: 'XII', grupo: 'L20-L30' },
  { codigo: 'L22', descripcion: 'Dermatitis del pañal', capitulo: 'XII', grupo: 'L20-L30' },
  { codigo: 'L23', descripcion: 'Dermatitis alérgica de contacto', capitulo: 'XII', grupo: 'L20-L30' },
  { codigo: 'L24', descripcion: 'Dermatitis de contacto por irritantes', capitulo: 'XII', grupo: 'L20-L30' },
  { codigo: 'L25', descripcion: 'Dermatitis de contacto, forma no especificada', capitulo: 'XII', grupo: 'L20-L30' },
  { codigo: 'L27', descripcion: 'Dermatitis debida a sustancias ingeridas', capitulo: 'XII', grupo: 'L20-L30' },
  { codigo: 'L29', descripcion: 'Prurito', capitulo: 'XII', grupo: 'L20-L30' },
  { codigo: 'L30', descripcion: 'Otras dermatitis', capitulo: 'XII', grupo: 'L20-L30' },
  { codigo: 'L40', descripcion: 'Psoriasis', capitulo: 'XII', grupo: 'L40-L45' },
  { codigo: 'L50', descripcion: 'Urticaria', capitulo: 'XII', grupo: 'L50-L54' },
  { codigo: 'L60', descripcion: 'Trastornos de las uñas', capitulo: 'XII', grupo: 'L60-L75' },
  { codigo: 'L63', descripcion: 'Alopecia areata', capitulo: 'XII', grupo: 'L60-L75' },
  { codigo: 'L65', descripcion: 'Otra pérdida no cicatricial del pelo', capitulo: 'XII', grupo: 'L60-L75' },
  { codigo: 'L70', descripcion: 'Acné', capitulo: 'XII', grupo: 'L60-L75' },
  { codigo: 'L72', descripcion: 'Quistes foliculares de la piel y del tejido subcutáneo', capitulo: 'XII', grupo: 'L60-L75' },
  { codigo: 'L80', descripcion: 'Vitiligo', capitulo: 'XII', grupo: 'L80-L99' },
  { codigo: 'L81', descripcion: 'Otros trastornos de la pigmentación', capitulo: 'XII', grupo: 'L80-L99' },
  { codigo: 'L82', descripcion: 'Queratosis seborreica', capitulo: 'XII', grupo: 'L80-L99' },
  { codigo: 'L84', descripcion: 'Callos y callosidades', capitulo: 'XII', grupo: 'L80-L99' },
  { codigo: 'L85', descripcion: 'Otros trastornos del engrosamiento de la epidermis', capitulo: 'XII', grupo: 'L80-L99' },
  { codigo: 'L90', descripcion: 'Trastornos atróficos de la piel', capitulo: 'XII', grupo: 'L80-L99' },
  { codigo: 'L91', descripcion: 'Trastornos hipertróficos de la piel', capitulo: 'XII', grupo: 'L80-L99' },
  { codigo: 'L98', descripcion: 'Otros trastornos de la piel y del tejido subcutáneo', capitulo: 'XII', grupo: 'L80-L99' },

  // CAPÍTULO XIII: Enfermedades del sistema osteomuscular (M00-M99)
  { codigo: 'M00', descripcion: 'Artritis piógena', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M05', descripcion: 'Artritis reumatoide seropositiva', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M06', descripcion: 'Otras artritis reumatoides', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M10', descripcion: 'Gota', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M13', descripcion: 'Otras artritis', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M15', descripcion: 'Poliartrosis', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M16', descripcion: 'Coxartrosis [artrosis de la cadera]', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M17', descripcion: 'Gonartrosis [artrosis de la rodilla]', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M19', descripcion: 'Otras artrosis', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M20', descripcion: 'Deformidades adquiridas de los dedos de la mano y del pie', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M21', descripcion: 'Otras deformidades adquiridas de los miembros', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M22', descripcion: 'Trastornos de la rótula', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M23', descripcion: 'Trastornos internos de la rodilla', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M24', descripcion: 'Otros trastornos articulares específicos', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M25', descripcion: 'Otros trastornos articulares, no clasificados en otra parte', capitulo: 'XIII', grupo: 'M00-M25' },
  { codigo: 'M32', descripcion: 'Lupus eritematoso sistémico', capitulo: 'XIII', grupo: 'M30-M36' },
  { codigo: 'M33', descripcion: 'Dermatopolimiositis', capitulo: 'XIII', grupo: 'M30-M36' },
  { codigo: 'M34', descripcion: 'Esclerosis sistémica', capitulo: 'XIII', grupo: 'M30-M36' },
  { codigo: 'M35', descripcion: 'Otros trastornos sistémicos del tejido conectivo', capitulo: 'XIII', grupo: 'M30-M36' },
  { codigo: 'M40', descripcion: 'Cifosis y lordosis', capitulo: 'XIII', grupo: 'M40-M54' },
  { codigo: 'M41', descripcion: 'Escoliosis', capitulo: 'XIII', grupo: 'M40-M54' },
  { codigo: 'M42', descripcion: 'Osteocondrosis de la columna vertebral', capitulo: 'XIII', grupo: 'M40-M54' },
  { codigo: 'M43', descripcion: 'Otras dorsopatías deformantes', capitulo: 'XIII', grupo: 'M40-M54' },
  { codigo: 'M45', descripcion: 'Espondilitis anquilosante', capitulo: 'XIII', grupo: 'M40-M54' },
  { codigo: 'M47', descripcion: 'Espondilosis', capitulo: 'XIII', grupo: 'M40-M54' },
  { codigo: 'M48', descripcion: 'Otras espondilopatías', capitulo: 'XIII', grupo: 'M40-M54' },
  { codigo: 'M50', descripcion: 'Trastornos de disco cervical', capitulo: 'XIII', grupo: 'M40-M54' },
  { codigo: 'M51', descripcion: 'Otros trastornos de los discos intervertebrales', capitulo: 'XIII', grupo: 'M40-M54' },
  { codigo: 'M53', descripcion: 'Otras dorsopatías, no clasificadas en otra parte', capitulo: 'XIII', grupo: 'M40-M54' },
  { codigo: 'M54', descripcion: 'Dorsalgia', capitulo: 'XIII', grupo: 'M40-M54' },
  { codigo: 'M60', descripcion: 'Miositis', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M62', descripcion: 'Otros trastornos de los músculos', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M65', descripcion: 'Sinovitis y tenosinovitis', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M66', descripcion: 'Ruptura espontánea de sinovial y de tendón', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M67', descripcion: 'Otros trastornos de la sinovial y del tendón', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M70', descripcion: 'Trastornos de los tejidos blandos relacionados con el uso, uso excesivo y presión', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M71', descripcion: 'Otras bursopatías', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M72', descripcion: 'Trastornos fibroblásticos', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M75', descripcion: 'Lesiones del hombro', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M76', descripcion: 'Entesopatías del miembro inferior, excluido el pie', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M77', descripcion: 'Otras entesopatías', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M79', descripcion: 'Otros trastornos de los tejidos blandos, no clasificados en otra parte', capitulo: 'XIII', grupo: 'M60-M79' },
  { codigo: 'M80', descripcion: 'Osteoporosis con fractura patológica', capitulo: 'XIII', grupo: 'M80-M94' },
  { codigo: 'M81', descripcion: 'Osteoporosis sin fractura patológica', capitulo: 'XIII', grupo: 'M80-M94' },
  { codigo: 'M84', descripcion: 'Trastornos de la continuidad del hueso', capitulo: 'XIII', grupo: 'M80-M94' },
  { codigo: 'M85', descripcion: 'Otros trastornos de la densidad y de la estructura óseas', capitulo: 'XIII', grupo: 'M80-M94' },
  { codigo: 'M86', descripcion: 'Osteomielitis', capitulo: 'XIII', grupo: 'M80-M94' },

  // CAPÍTULO XIV: Enfermedades del sistema genitourinario (N00-N99)
  { codigo: 'N00', descripcion: 'Síndrome nefrítico agudo', capitulo: 'XIV', grupo: 'N00-N08' },
  { codigo: 'N03', descripcion: 'Síndrome nefrítico crónico', capitulo: 'XIV', grupo: 'N00-N08' },
  { codigo: 'N04', descripcion: 'Síndrome nefrótico', capitulo: 'XIV', grupo: 'N00-N08' },
  { codigo: 'N05', descripcion: 'Síndrome nefrítico no especificado', capitulo: 'XIV', grupo: 'N00-N08' },
  { codigo: 'N10', descripcion: 'Nefritis tubulointersticial aguda', capitulo: 'XIV', grupo: 'N10-N16' },
  { codigo: 'N11', descripcion: 'Nefritis tubulointersticial crónica', capitulo: 'XIV', grupo: 'N10-N16' },
  { codigo: 'N12', descripcion: 'Nefritis tubulointersticial, no especificada como aguda o crónica', capitulo: 'XIV', grupo: 'N10-N16' },
  { codigo: 'N17', descripcion: 'Insuficiencia renal aguda', capitulo: 'XIV', grupo: 'N17-N19' },
  { codigo: 'N18', descripcion: 'Insuficiencia renal crónica', capitulo: 'XIV', grupo: 'N17-N19' },
  { codigo: 'N19', descripcion: 'Insuficiencia renal no especificada', capitulo: 'XIV', grupo: 'N17-N19' },
  { codigo: 'N20', descripcion: 'Cálculo del riñón y del uréter', capitulo: 'XIV', grupo: 'N20-N23' },
  { codigo: 'N21', descripcion: 'Cálculo de las vías urinarias inferiores', capitulo: 'XIV', grupo: 'N20-N23' },
  { codigo: 'N23', descripcion: 'Cólico renal, no especificado', capitulo: 'XIV', grupo: 'N20-N23' },
  { codigo: 'N28', descripcion: 'Otros trastornos del riñón y del uréter', capitulo: 'XIV', grupo: 'N25-N29' },
  { codigo: 'N30', descripcion: 'Cistitis', capitulo: 'XIV', grupo: 'N30-N39' },
  { codigo: 'N32', descripcion: 'Otros trastornos de la vejiga', capitulo: 'XIV', grupo: 'N30-N39' },
  { codigo: 'N34', descripcion: 'Uretritis y síndrome uretral', capitulo: 'XIV', grupo: 'N30-N39' },
  { codigo: 'N39', descripcion: 'Otros trastornos del sistema urinario', capitulo: 'XIV', grupo: 'N30-N39' },
  { codigo: 'N40', descripcion: 'Hiperplasia de la próstata', capitulo: 'XIV', grupo: 'N40-N51' },
  { codigo: 'N41', descripcion: 'Enfermedades inflamatorias de la próstata', capitulo: 'XIV', grupo: 'N40-N51' },
  { codigo: 'N42', descripcion: 'Otros trastornos de la próstata', capitulo: 'XIV', grupo: 'N40-N51' },
  { codigo: 'N43', descripcion: 'Hidrocele y espermatocele', capitulo: 'XIV', grupo: 'N40-N51' },
  { codigo: 'N44', descripcion: 'Torsión del testículo', capitulo: 'XIV', grupo: 'N40-N51' },
  { codigo: 'N45', descripcion: 'Orquitis y epididimitis', capitulo: 'XIV', grupo: 'N40-N51' },
  { codigo: 'N46', descripcion: 'Esterilidad masculina', capitulo: 'XIV', grupo: 'N40-N51' },
  { codigo: 'N48', descripcion: 'Otros trastornos del pene', capitulo: 'XIV', grupo: 'N40-N51' },
  { codigo: 'N60', descripcion: 'Displasia mamaria benigna', capitulo: 'XIV', grupo: 'N60-N64' },
  { codigo: 'N61', descripcion: 'Trastornos inflamatorios de la mama', capitulo: 'XIV', grupo: 'N60-N64' },
  { codigo: 'N62', descripcion: 'Hipertrofia de la mama', capitulo: 'XIV', grupo: 'N60-N64' },
  { codigo: 'N63', descripcion: 'Masa no especificada en la mama', capitulo: 'XIV', grupo: 'N60-N64' },
  { codigo: 'N64', descripcion: 'Otros trastornos de la mama', capitulo: 'XIV', grupo: 'N60-N64' },
  { codigo: 'N70', descripcion: 'Salpingitis y ooforitis', capitulo: 'XIV', grupo: 'N70-N77' },
  { codigo: 'N71', descripcion: 'Enfermedad inflamatoria del útero, excepto del cuello', capitulo: 'XIV', grupo: 'N70-N77' },
  { codigo: 'N72', descripcion: 'Enfermedad inflamatoria del cuello uterino', capitulo: 'XIV', grupo: 'N70-N77' },
  { codigo: 'N73', descripcion: 'Otras enfermedades inflamatorias pélvicas femeninas', capitulo: 'XIV', grupo: 'N70-N77' },
  { codigo: 'N75', descripcion: 'Enfermedades de las glándulas de Bartolino', capitulo: 'XIV', grupo: 'N70-N77' },
  { codigo: 'N76', descripcion: 'Otras enfermedades inflamatorias de la vagina y de la vulva', capitulo: 'XIV', grupo: 'N70-N77' },
  { codigo: 'N80', descripcion: 'Endometriosis', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N81', descripcion: 'Prolapso genital femenino', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N83', descripcion: 'Trastornos no inflamatorios del ovario, trompa de Falopio y ligamento ancho', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N84', descripcion: 'Pólipo del tracto genital femenino', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N85', descripcion: 'Otros trastornos no inflamatorios del útero, excepto del cuello', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N87', descripcion: 'Displasia del cuello uterino', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N89', descripcion: 'Otros trastornos no inflamatorios de la vagina', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N91', descripcion: 'Menstruación ausente, escasa o infrecuente', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N92', descripcion: 'Menstruación excesiva, frecuente e irregular', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N93', descripcion: 'Otras hemorragias uterinas o vaginales anormales', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N94', descripcion: 'Dolor y otras afecciones relacionadas con órganos genitales femeninos', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N95', descripcion: 'Trastornos menopáusicos y otros perimenopáusicos', capitulo: 'XIV', grupo: 'N80-N98' },
  { codigo: 'N97', descripcion: 'Esterilidad femenina', capitulo: 'XIV', grupo: 'N80-N98' },

  // CAPÍTULO XV: Embarazo, parto y puerperio (O00-O99)
  { codigo: 'O00', descripcion: 'Embarazo ectópico', capitulo: 'XV', grupo: 'O00-O08' },
  { codigo: 'O03', descripcion: 'Aborto espontáneo', capitulo: 'XV', grupo: 'O00-O08' },
  { codigo: 'O10', descripcion: 'Hipertensión preexistente que complica el embarazo', capitulo: 'XV', grupo: 'O10-O16' },
  { codigo: 'O11', descripcion: 'Trastornos hipertensivos preexistentes con proteinuria agregada', capitulo: 'XV', grupo: 'O10-O16' },
  { codigo: 'O12', descripcion: 'Edema y proteinuria gestacionales sin hipertensión', capitulo: 'XV', grupo: 'O10-O16' },
  { codigo: 'O13', descripcion: 'Hipertensión gestacional sin proteinuria significativa', capitulo: 'XV', grupo: 'O10-O16' },
  { codigo: 'O14', descripcion: 'Hipertensión gestacional con proteinuria significativa', capitulo: 'XV', grupo: 'O10-O16' },
  { codigo: 'O15', descripcion: 'Eclampsia', capitulo: 'XV', grupo: 'O10-O16' },
  { codigo: 'O20', descripcion: 'Hemorragia precoz del embarazo', capitulo: 'XV', grupo: 'O20-O29' },
  { codigo: 'O21', descripcion: 'Vómitos excesivos en el embarazo', capitulo: 'XV', grupo: 'O20-O29' },
  { codigo: 'O23', descripcion: 'Infecciones de las vías genitourinarias en el embarazo', capitulo: 'XV', grupo: 'O20-O29' },
  { codigo: 'O24', descripcion: 'Diabetes mellitus en el embarazo', capitulo: 'XV', grupo: 'O20-O29' },
  { codigo: 'O26', descripcion: 'Atención a la madre por otras complicaciones', capitulo: 'XV', grupo: 'O20-O29' },
  { codigo: 'O30', descripcion: 'Embarazo múltiple', capitulo: 'XV', grupo: 'O30-O48' },
  { codigo: 'O34', descripcion: 'Atención materna por anomalía conocida o sospechada de los órganos pelvianos', capitulo: 'XV', grupo: 'O30-O48' },
  { codigo: 'O36', descripcion: 'Atención materna por otros problemas fetales conocidos o sospechados', capitulo: 'XV', grupo: 'O30-O48' },
  { codigo: 'O40', descripcion: 'Polihidramnios', capitulo: 'XV', grupo: 'O30-O48' },
  { codigo: 'O41', descripcion: 'Otros trastornos del líquido amniótico y de las membranas', capitulo: 'XV', grupo: 'O30-O48' },
  { codigo: 'O42', descripcion: 'Ruptura prematura de las membranas', capitulo: 'XV', grupo: 'O30-O48' },
  { codigo: 'O44', descripcion: 'Placenta previa', capitulo: 'XV', grupo: 'O30-O48' },
  { codigo: 'O45', descripcion: 'Desprendimiento prematuro de la placenta', capitulo: 'XV', grupo: 'O30-O48' },
  { codigo: 'O46', descripcion: 'Hemorragia anteparto, no clasificada en otra parte', capitulo: 'XV', grupo: 'O30-O48' },
  { codigo: 'O47', descripcion: 'Falso trabajo de parto', capitulo: 'XV', grupo: 'O30-O48' },
  { codigo: 'O60', descripcion: 'Parto prematuro', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O62', descripcion: 'Anormalidades de la dinámica del trabajo de parto', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O63', descripcion: 'Trabajo de parto prolongado', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O64', descripcion: 'Trabajo de parto obstruido debido a mala posición y presentación anormales del feto', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O66', descripcion: 'Otras obstrucciones del trabajo de parto', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O68', descripcion: 'Trabajo de parto y parto complicados por sufrimiento fetal', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O69', descripcion: 'Trabajo de parto y parto complicados por problemas del cordón umbilical', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O70', descripcion: 'Desgarro perineal durante el parto', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O71', descripcion: 'Otro trauma obstétrico', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O72', descripcion: 'Hemorragia postparto', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O73', descripcion: 'Retención de placenta y membranas sin hemorragia', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O75', descripcion: 'Otras complicaciones del trabajo de parto y del parto', capitulo: 'XV', grupo: 'O60-O75' },
  { codigo: 'O80', descripcion: 'Parto único espontáneo', capitulo: 'XV', grupo: 'O80-O84' },
  { codigo: 'O82', descripcion: 'Parto único por cesárea', capitulo: 'XV', grupo: 'O80-O84' },
  { codigo: 'O85', descripcion: 'Sepsis puerperal', capitulo: 'XV', grupo: 'O85-O92' },
  { codigo: 'O86', descripcion: 'Otras infecciones puerperales', capitulo: 'XV', grupo: 'O85-O92' },
  { codigo: 'O90', descripcion: 'Complicaciones del puerperio, no clasificadas en otra parte', capitulo: 'XV', grupo: 'O85-O92' },
  { codigo: 'O91', descripcion: 'Infecciones de la mama asociadas con el parto', capitulo: 'XV', grupo: 'O85-O92' },
  { codigo: 'O92', descripcion: 'Otros trastornos de la mama y de la lactancia asociados con el parto', capitulo: 'XV', grupo: 'O85-O92' },
  { codigo: 'O99', descripcion: 'Otras enfermedades maternas que complican el embarazo', capitulo: 'XV', grupo: 'O95-O99' },

  // CAPÍTULO XVIII: Síntomas, signos y hallazgos anormales (R00-R99)
  { codigo: 'R00', descripcion: 'Anormalidades del latido cardíaco', capitulo: 'XVIII', grupo: 'R00-R09' },
  { codigo: 'R04', descripcion: 'Hemorragia de las vías respiratorias', capitulo: 'XVIII', grupo: 'R00-R09' },
  { codigo: 'R05', descripcion: 'Tos', capitulo: 'XVIII', grupo: 'R00-R09' },
  { codigo: 'R06', descripcion: 'Anormalidades de la respiración', capitulo: 'XVIII', grupo: 'R00-R09' },
  { codigo: 'R07', descripcion: 'Dolor de garganta y en el pecho', capitulo: 'XVIII', grupo: 'R00-R09' },
  { codigo: 'R10', descripcion: 'Dolor abdominal y pélvico', capitulo: 'XVIII', grupo: 'R10-R19' },
  { codigo: 'R11', descripcion: 'Náusea y vómito', capitulo: 'XVIII', grupo: 'R10-R19' },
  { codigo: 'R13', descripcion: 'Disfagia', capitulo: 'XVIII', grupo: 'R10-R19' },
  { codigo: 'R14', descripcion: 'Flatulencia y afecciones afines', capitulo: 'XVIII', grupo: 'R10-R19' },
  { codigo: 'R17', descripcion: 'Ictericia no especificada', capitulo: 'XVIII', grupo: 'R10-R19' },
  { codigo: 'R19', descripcion: 'Otros síntomas y signos que involucran el sistema digestivo y el abdomen', capitulo: 'XVIII', grupo: 'R10-R19' },
  { codigo: 'R20', descripcion: 'Alteraciones de la sensibilidad cutánea', capitulo: 'XVIII', grupo: 'R20-R23' },
  { codigo: 'R21', descripcion: 'Salpullido y otras erupciones cutáneas no específicas', capitulo: 'XVIII', grupo: 'R20-R23' },
  { codigo: 'R22', descripcion: 'Tumefacción, masa o bulto localizados en piel y tejido subcutáneo', capitulo: 'XVIII', grupo: 'R20-R23' },
  { codigo: 'R25', descripcion: 'Movimientos involuntarios anormales', capitulo: 'XVIII', grupo: 'R25-R29' },
  { codigo: 'R26', descripcion: 'Anormalidades de la marcha y de la movilidad', capitulo: 'XVIII', grupo: 'R25-R29' },
  { codigo: 'R27', descripcion: 'Otras fallas de coordinación', capitulo: 'XVIII', grupo: 'R25-R29' },
  { codigo: 'R29', descripcion: 'Otros síntomas y signos que involucran sistemas nervioso y osteomuscular', capitulo: 'XVIII', grupo: 'R25-R29' },
  { codigo: 'R30', descripcion: 'Dolor asociado con la micción', capitulo: 'XVIII', grupo: 'R30-R39' },
  { codigo: 'R31', descripcion: 'Hematuria, no especificada', capitulo: 'XVIII', grupo: 'R30-R39' },
  { codigo: 'R32', descripcion: 'Incontinencia urinaria, no especificada', capitulo: 'XVIII', grupo: 'R30-R39' },
  { codigo: 'R33', descripcion: 'Retención de orina', capitulo: 'XVIII', grupo: 'R30-R39' },
  { codigo: 'R35', descripcion: 'Poliuria', capitulo: 'XVIII', grupo: 'R30-R39' },
  { codigo: 'R39', descripcion: 'Otros síntomas y signos que involucran el sistema urinario', capitulo: 'XVIII', grupo: 'R30-R39' },
  { codigo: 'R40', descripcion: 'Somnolencia, estupor y coma', capitulo: 'XVIII', grupo: 'R40-R46' },
  { codigo: 'R41', descripcion: 'Otros síntomas y signos que involucran función cognoscitiva y conciencia', capitulo: 'XVIII', grupo: 'R40-R46' },
  { codigo: 'R42', descripcion: 'Mareo y desvanecimiento', capitulo: 'XVIII', grupo: 'R40-R46' },
  { codigo: 'R45', descripcion: 'Síntomas y signos que involucran el estado emocional', capitulo: 'XVIII', grupo: 'R40-R46' },
  { codigo: 'R50', descripcion: 'Fiebre de otro origen desconocido', capitulo: 'XVIII', grupo: 'R50-R69' },
  { codigo: 'R51', descripcion: 'Cefalea', capitulo: 'XVIII', grupo: 'R50-R69' },
  { codigo: 'R52', descripcion: 'Dolor, no clasificado en otra parte', capitulo: 'XVIII', grupo: 'R50-R69' },
  { codigo: 'R53', descripcion: 'Malestar y fatiga', capitulo: 'XVIII', grupo: 'R50-R69' },
  { codigo: 'R55', descripcion: 'Síncope y colapso', capitulo: 'XVIII', grupo: 'R50-R69' },
  { codigo: 'R56', descripcion: 'Convulsiones, no clasificadas en otra parte', capitulo: 'XVIII', grupo: 'R50-R69' },
  { codigo: 'R59', descripcion: 'Adenomegalia', capitulo: 'XVIII', grupo: 'R50-R69' },
  { codigo: 'R60', descripcion: 'Edema, no clasificado en otra parte', capitulo: 'XVIII', grupo: 'R50-R69' },
  { codigo: 'R63', descripcion: 'Síntomas y signos concernientes a la alimentación y a la ingestión de líquidos', capitulo: 'XVIII', grupo: 'R50-R69' },
  { codigo: 'R68', descripcion: 'Otros síntomas y signos generales', capitulo: 'XVIII', grupo: 'R50-R69' },
  { codigo: 'R69', descripcion: 'Causas de morbilidad desconocidas y no especificadas', capitulo: 'XVIII', grupo: 'R50-R69' },

  // CAPÍTULO XIX: Traumatismos y envenenamientos (S00-T98)
  { codigo: 'S00', descripcion: 'Traumatismo superficial de la cabeza', capitulo: 'XIX', grupo: 'S00-S09' },
  { codigo: 'S01', descripcion: 'Herida de la cabeza', capitulo: 'XIX', grupo: 'S00-S09' },
  { codigo: 'S02', descripcion: 'Fractura del cráneo y de los huesos de la cara', capitulo: 'XIX', grupo: 'S00-S09' },
  { codigo: 'S06', descripcion: 'Traumatismo intracraneal', capitulo: 'XIX', grupo: 'S00-S09' },
  { codigo: 'S09', descripcion: 'Otros traumatismos y los no especificados de la cabeza', capitulo: 'XIX', grupo: 'S00-S09' },
  { codigo: 'S10', descripcion: 'Traumatismo superficial del cuello', capitulo: 'XIX', grupo: 'S10-S19' },
  { codigo: 'S12', descripcion: 'Fractura del cuello', capitulo: 'XIX', grupo: 'S10-S19' },
  { codigo: 'S13', descripcion: 'Luxación, esguince y torcedura de articulaciones y ligamentos del cuello', capitulo: 'XIX', grupo: 'S10-S19' },
  { codigo: 'S20', descripcion: 'Traumatismo superficial del tórax', capitulo: 'XIX', grupo: 'S20-S29' },
  { codigo: 'S22', descripcion: 'Fractura de la costilla, del esternón y de la columna torácica', capitulo: 'XIX', grupo: 'S20-S29' },
  { codigo: 'S27', descripcion: 'Traumatismo de otros órganos intratorácicos', capitulo: 'XIX', grupo: 'S20-S29' },
  { codigo: 'S30', descripcion: 'Traumatismo superficial del abdomen, de la región lumbosacra y de la pelvis', capitulo: 'XIX', grupo: 'S30-S39' },
  { codigo: 'S32', descripcion: 'Fractura de la columna lumbar y de la pelvis', capitulo: 'XIX', grupo: 'S30-S39' },
  { codigo: 'S33', descripcion: 'Luxación, esguince y torcedura de articulaciones y ligamentos de la columna lumbar y pelvis', capitulo: 'XIX', grupo: 'S30-S39' },
  { codigo: 'S40', descripcion: 'Traumatismo superficial del hombro y del brazo', capitulo: 'XIX', grupo: 'S40-S49' },
  { codigo: 'S42', descripcion: 'Fractura del hombro y del brazo', capitulo: 'XIX', grupo: 'S40-S49' },
  { codigo: 'S43', descripcion: 'Luxación, esguince y torcedura de articulaciones y ligamentos de la cintura escapular', capitulo: 'XIX', grupo: 'S40-S49' },
  { codigo: 'S50', descripcion: 'Traumatismo superficial del antebrazo y del codo', capitulo: 'XIX', grupo: 'S50-S59' },
  { codigo: 'S52', descripcion: 'Fractura del antebrazo', capitulo: 'XIX', grupo: 'S50-S59' },
  { codigo: 'S53', descripcion: 'Luxación, esguince y torcedura de articulaciones y ligamentos del codo', capitulo: 'XIX', grupo: 'S50-S59' },
  { codigo: 'S60', descripcion: 'Traumatismo superficial de la muñeca y de la mano', capitulo: 'XIX', grupo: 'S60-S69' },
  { codigo: 'S61', descripcion: 'Herida de la muñeca y de la mano', capitulo: 'XIX', grupo: 'S60-S69' },
  { codigo: 'S62', descripcion: 'Fractura a nivel de la muñeca y de la mano', capitulo: 'XIX', grupo: 'S60-S69' },
  { codigo: 'S63', descripcion: 'Luxación, esguince y torcedura de articulaciones y ligamentos a nivel de la muñeca y de la mano', capitulo: 'XIX', grupo: 'S60-S69' },
  { codigo: 'S70', descripcion: 'Traumatismo superficial de la cadera y del muslo', capitulo: 'XIX', grupo: 'S70-S79' },
  { codigo: 'S72', descripcion: 'Fractura del fémur', capitulo: 'XIX', grupo: 'S70-S79' },
  { codigo: 'S73', descripcion: 'Luxación, esguince y torcedura de articulación y ligamentos de la cadera', capitulo: 'XIX', grupo: 'S70-S79' },
  { codigo: 'S80', descripcion: 'Traumatismo superficial de la pierna', capitulo: 'XIX', grupo: 'S80-S89' },
  { codigo: 'S82', descripcion: 'Fractura de la pierna, inclusive el tobillo', capitulo: 'XIX', grupo: 'S80-S89' },
  { codigo: 'S83', descripcion: 'Luxación, esguince y torcedura de articulaciones y ligamentos de la rodilla', capitulo: 'XIX', grupo: 'S80-S89' },
  { codigo: 'S90', descripcion: 'Traumatismo superficial del tobillo y del pie', capitulo: 'XIX', grupo: 'S90-S99' },
  { codigo: 'S92', descripcion: 'Fractura del pie, excepto del tobillo', capitulo: 'XIX', grupo: 'S90-S99' },
  { codigo: 'S93', descripcion: 'Luxación, esguince y torcedura de articulaciones y ligamentos del tobillo y del pie', capitulo: 'XIX', grupo: 'S90-S99' },
  { codigo: 'T00', descripcion: 'Traumatismos superficiales que afectan múltiples regiones del cuerpo', capitulo: 'XIX', grupo: 'T00-T07' },
  { codigo: 'T14', descripcion: 'Traumatismo de región del cuerpo no especificada', capitulo: 'XIX', grupo: 'T08-T14' },
  { codigo: 'T30', descripcion: 'Quemadura y corrosión, región del cuerpo no especificada', capitulo: 'XIX', grupo: 'T20-T32' },
  { codigo: 'T36', descripcion: 'Envenenamiento por antibióticos sistémicos', capitulo: 'XIX', grupo: 'T36-T50' },
  { codigo: 'T78', descripcion: 'Efectos adversos, no clasificados en otra parte', capitulo: 'XIX', grupo: 'T66-T78' },
  { codigo: 'T79', descripcion: 'Algunas complicaciones precoces de los traumatismos', capitulo: 'XIX', grupo: 'T79' },
  { codigo: 'T81', descripcion: 'Complicaciones de procedimientos, no clasificadas en otra parte', capitulo: 'XIX', grupo: 'T80-T88' },
  { codigo: 'T88', descripcion: 'Otras complicaciones de la atención médica y quirúrgica', capitulo: 'XIX', grupo: 'T80-T88' },

  // CAPÍTULO XXI: Factores que influyen en el estado de salud (Z00-Z99)
  { codigo: 'Z00', descripcion: 'Examen general e investigación de personas sin quejas o sin diagnóstico informado', capitulo: 'XXI', grupo: 'Z00-Z13' },
  { codigo: 'Z01', descripcion: 'Otros exámenes e investigaciones especiales de personas sin quejas o sin diagnóstico informado', capitulo: 'XXI', grupo: 'Z00-Z13' },
  { codigo: 'Z02', descripcion: 'Examen y observación por razones administrativas', capitulo: 'XXI', grupo: 'Z00-Z13' },
  { codigo: 'Z03', descripcion: 'Observación y evaluación médicas por sospecha de enfermedades y afecciones', capitulo: 'XXI', grupo: 'Z00-Z13' },
  { codigo: 'Z10', descripcion: 'Examen general de salud de rutina de una subpoblación definida', capitulo: 'XXI', grupo: 'Z00-Z13' },
  { codigo: 'Z12', descripcion: 'Examen de pesquisa especial para tumores', capitulo: 'XXI', grupo: 'Z00-Z13' },
  { codigo: 'Z13', descripcion: 'Examen de pesquisa especial para otras enfermedades y trastornos', capitulo: 'XXI', grupo: 'Z00-Z13' },
  { codigo: 'Z20', descripcion: 'Contacto con y exposición a enfermedades transmisibles', capitulo: 'XXI', grupo: 'Z20-Z29' },
  { codigo: 'Z21', descripcion: 'Estado de infección asintomática por el VIH', capitulo: 'XXI', grupo: 'Z20-Z29' },
  { codigo: 'Z23', descripcion: 'Necesidad de inmunización contra una sola enfermedad bacteriana', capitulo: 'XXI', grupo: 'Z20-Z29' },
  { codigo: 'Z24', descripcion: 'Necesidad de inmunización contra ciertas enfermedades virales individuales', capitulo: 'XXI', grupo: 'Z20-Z29' },
  { codigo: 'Z25', descripcion: 'Necesidad de inmunización contra otras enfermedades virales individuales', capitulo: 'XXI', grupo: 'Z20-Z29' },
  { codigo: 'Z27', descripcion: 'Necesidad de inmunización contra combinaciones de enfermedades infecciosas', capitulo: 'XXI', grupo: 'Z20-Z29' },
  { codigo: 'Z30', descripcion: 'Atención para la anticoncepción', capitulo: 'XXI', grupo: 'Z30-Z39' },
  { codigo: 'Z32', descripcion: 'Examen y prueba del embarazo', capitulo: 'XXI', grupo: 'Z30-Z39' },
  { codigo: 'Z33', descripcion: 'Estado de embarazo, incidental', capitulo: 'XXI', grupo: 'Z30-Z39' },
  { codigo: 'Z34', descripcion: 'Supervisión de embarazo normal', capitulo: 'XXI', grupo: 'Z30-Z39' },
  { codigo: 'Z35', descripcion: 'Supervisión de embarazo de alto riesgo', capitulo: 'XXI', grupo: 'Z30-Z39' },
  { codigo: 'Z36', descripcion: 'Pesquisa prenatal', capitulo: 'XXI', grupo: 'Z30-Z39' },
  { codigo: 'Z39', descripcion: 'Examen y atención del postparto', capitulo: 'XXI', grupo: 'Z30-Z39' },
  { codigo: 'Z71', descripcion: 'Personas en contacto con los servicios de salud para otros consejos e instrucción médica', capitulo: 'XXI', grupo: 'Z70-Z76' },
  { codigo: 'Z76', descripcion: 'Personas que tienen contacto con los servicios de salud en otras circunstancias', capitulo: 'XXI', grupo: 'Z70-Z76' },
  { codigo: 'Z86', descripcion: 'Historia personal de ciertas otras enfermedades', capitulo: 'XXI', grupo: 'Z80-Z99' },
  { codigo: 'Z87', descripcion: 'Historia personal de otras enfermedades y afecciones', capitulo: 'XXI', grupo: 'Z80-Z99' },
  { codigo: 'Z88', descripcion: 'Historia personal de alergia a drogas, medicamentos y sustancias biológicas', capitulo: 'XXI', grupo: 'Z80-Z99' },
  { codigo: 'Z91', descripcion: 'Historia personal de factores de riesgo, no clasificados en otra parte', capitulo: 'XXI', grupo: 'Z80-Z99' },
  { codigo: 'Z96', descripcion: 'Presencia de otros implantes funcionales', capitulo: 'XXI', grupo: 'Z80-Z99' },
];

async function main() {
  console.log('🏥 Iniciando seeding de catálogo CIE-10...\n');

  let created = 0;
  let skipped = 0;

  for (const item of CIE10_CODIGOS) {
    try {
      await prisma.catalogoCie10.upsert({
        where: { codigo: item.codigo },
        update: {
          descripcion: item.descripcion,
          capitulo: item.capitulo,
          grupo: item.grupo,
        },
        create: {
          codigo: item.codigo,
          descripcion: item.descripcion,
          capitulo: item.capitulo,
          grupo: item.grupo,
          estado: 'Activo',
        },
      });
      created++;
    } catch (error) {
      console.error(`Error con código ${item.codigo}:`, error.message);
      skipped++;
    }
  }

  console.log(`\n✅ Seeding completado:`);
  console.log(`   - Códigos procesados: ${created}`);
  console.log(`   - Códigos omitidos: ${skipped}`);
  console.log(`   - Total en catálogo: ${CIE10_CODIGOS.length}`);
}

main()
  .catch((e) => {
    console.error('❌ Error en seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
