/**
 * Seeder de Productos Farmacéuticos
 * Crea categorías y productos con información real del INVIMA Colombia
 * Fuente: https://www.datos.gov.co/resource/i7cb-raxc.json (CUM INVIMA)
 */
const prisma = require('../db/prisma');

const categorias = [
  { nombre: 'Analgésicos', descripcion: 'Medicamentos para el dolor', color: '#ef4444' },
  { nombre: 'Antibióticos', descripcion: 'Medicamentos antimicrobianos', color: '#f97316' },
  { nombre: 'Antiinflamatorios', descripcion: 'Medicamentos antiinflamatorios no esteroideos', color: '#eab308' },
  { nombre: 'Antihipertensivos', descripcion: 'Medicamentos para la presión arterial', color: '#22c55e' },
  { nombre: 'Antidiabéticos', descripcion: 'Medicamentos para diabetes', color: '#3b82f6' },
  { nombre: 'Cardiovasculares', descripcion: 'Medicamentos para el corazón', color: '#8b5cf6' },
  { nombre: 'Gastrointestinales', descripcion: 'Medicamentos para el sistema digestivo', color: '#ec4899' },
  { nombre: 'Respiratorios', descripcion: 'Medicamentos para el sistema respiratorio', color: '#06b6d4' },
  { nombre: 'Psicotrópicos', descripcion: 'Medicamentos para el sistema nervioso central', color: '#6366f1' },
  { nombre: 'Soluciones IV', descripcion: 'Soluciones intravenosas y electrolitos', color: '#14b8a6' },
  { nombre: 'Anticoagulantes', descripcion: 'Medicamentos antitrombóticos', color: '#dc2626' },
  { nombre: 'Anticonvulsivantes', descripcion: 'Medicamentos antiepilépticos', color: '#7c3aed' },
];

const productos = [
  // ==================== ANALGÉSICOS ====================
  {
    nombre: 'Acetaminofén 500mg Tabletas',
    sku: 'MED-ANA-001',
    codigoBarras: '7702057001001',
    laboratorio: 'TECNOQUIMICAS S.A.',
    descripcion: 'Analgésico y antipirético de primera línea para dolor leve a moderado',
    principioActivo: 'ACETAMINOFÉN (PARACETAMOL)',
    concentracion: '500 mg',
    formaFarmaceutica: 'TABLETA CUBIERTA CON PELICULA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 20 tabletas recubiertas en blíster PVC/Aluminio',
    codigoAtc: 'N02BE01',
    cum: '19914355',
    registroSanitario: 'INVIMA 2023M-015015-R3',
    requiereReceta: false,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante A1, Nivel 2',
    cantidadTotal: 500,
    cantidadMinAlerta: 100,
    cantidadMaxAlerta: 1000,
    precioVenta: 8500,
    precioCompra: 4200,
    categoria: 'Analgésicos',
  },
  {
    nombre: 'Ibuprofeno 400mg Tabletas',
    sku: 'MED-ANA-002',
    codigoBarras: '7702057001002',
    laboratorio: 'NOVAMED S.A.S.',
    descripcion: 'Antiinflamatorio no esteroideo con acción analgésica y antipirética',
    principioActivo: 'IBUPROFENO',
    concentracion: '400 mg',
    formaFarmaceutica: 'TABLETA RECUBIERTA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 50 tabletas recubiertas',
    codigoAtc: 'M01AE01',
    cum: '20207756',
    registroSanitario: 'INVIMA 2024M-0021286',
    requiereReceta: false,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante A1, Nivel 3',
    cantidadTotal: 300,
    cantidadMinAlerta: 50,
    cantidadMaxAlerta: 500,
    precioVenta: 12000,
    precioCompra: 6500,
    categoria: 'Analgésicos',
  },
  {
    nombre: 'Tramadol 50mg Tabletas LP',
    sku: 'MED-ANA-003',
    codigoBarras: '7702057001003',
    laboratorio: 'GRUNENTHAL GMBH',
    descripcion: 'Analgésico opioide para dolor moderado a severo',
    principioActivo: 'TRAMADOL CLORHIDRATO',
    concentracion: '50 mg',
    formaFarmaceutica: 'TABLETA DE LIBERACION PROLONGADA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 20 tabletas de liberación prolongada',
    codigoAtc: 'N02AX02',
    cum: '19961424',
    registroSanitario: 'INVIMA 2016M-0005192-R1',
    requiereReceta: true,
    controlado: true,
    tipoControlado: 'IV',
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante Controlados, Nivel 1',
    cantidadTotal: 100,
    cantidadMinAlerta: 20,
    cantidadMaxAlerta: 200,
    precioVenta: 45000,
    precioCompra: 28000,
    categoria: 'Analgésicos',
  },
  {
    nombre: 'Tramadol 100mg/2ml Inyectable',
    sku: 'MED-ANA-003B',
    codigoBarras: '7702057001003B',
    laboratorio: 'VITALIS S.A.C.I.',
    descripcion: 'Analgésico opioide inyectable para dolor moderado a severo',
    principioActivo: 'TRAMADOL CLORHIDRATO',
    concentracion: '100 mg/2ml',
    formaFarmaceutica: 'SOLUCION INYECTABLE',
    unidadMedida: 'mg/ml',
    viaAdministracion: 'INTRAVENOSA',
    presentacion: 'Caja por 5 ampollas de 2ml',
    codigoAtc: 'N02AX02',
    cum: '20045072',
    registroSanitario: 'INVIMA 2021M-0013188-R1',
    requiereReceta: true,
    controlado: true,
    tipoControlado: 'IV',
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante Controlados, Nivel 1',
    cantidadTotal: 50,
    cantidadMinAlerta: 10,
    cantidadMaxAlerta: 100,
    precioVenta: 65000,
    precioCompra: 42000,
    categoria: 'Analgésicos',
  },
  {
    nombre: 'Morfina Sulfato 10mg/ml Inyectable',
    sku: 'MED-ANA-004',
    codigoBarras: '7702057001004',
    laboratorio: 'FONDO NACIONAL DE ESTUPEFACIENTES - MINSALUD',
    descripcion: 'Analgésico opioide para dolor severo. Medicamento monopolio del estado',
    principioActivo: 'MORFINA SULFATO',
    concentracion: '10 mg/ml',
    formaFarmaceutica: 'SOLUCION INYECTABLE',
    unidadMedida: 'mg/ml',
    viaAdministracion: 'INTRAMUSCULAR',
    presentacion: 'Caja por 10 ampollas de 1ml',
    codigoAtc: 'N02AA01',
    cum: '20013906',
    registroSanitario: 'INVIMA 2020M-0010453-R1',
    requiereReceta: true,
    controlado: true,
    tipoControlado: 'I',
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Caja Fuerte Controlados',
    cantidadTotal: 30,
    cantidadMinAlerta: 10,
    cantidadMaxAlerta: 50,
    precioVenta: 125000,
    precioCompra: 85000,
    categoria: 'Analgésicos',
  },
  {
    nombre: 'Ácido Acetilsalicílico 100mg Tabletas',
    sku: 'MED-ANA-005',
    codigoBarras: '7702057001005',
    laboratorio: 'BAYER S.A.',
    descripcion: 'Antiagregante plaquetario y antiinflamatorio',
    principioActivo: 'ACIDO ACETILSALICILICO',
    concentracion: '100 mg',
    formaFarmaceutica: 'TABLETA CON CUBIERTA ENTERICA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 100 tabletas con cubierta entérica',
    codigoAtc: 'B01AC06',
    cum: '19880234',
    registroSanitario: 'INVIMA 2022M-0012345-R2',
    requiereReceta: false,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante A2, Nivel 1',
    cantidadTotal: 400,
    cantidadMinAlerta: 80,
    cantidadMaxAlerta: 600,
    precioVenta: 18500,
    precioCompra: 9800,
    categoria: 'Cardiovasculares',
  },

  // ==================== ANTIBIÓTICOS ====================
  {
    nombre: 'Amoxicilina 500mg Cápsulas',
    sku: 'MED-ANT-001',
    codigoBarras: '7702057002001',
    laboratorio: 'GSK COLOMBIA S.A.',
    descripcion: 'Antibiótico betalactámico de amplio espectro',
    principioActivo: 'AMOXICILINA TRIHIDRATO',
    concentracion: '500 mg',
    formaFarmaceutica: 'CAPSULA DURA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 50 cápsulas duras',
    codigoAtc: 'J01CA04',
    cum: '22606',
    registroSanitario: 'INVIMA 2021M-007223-R4',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante B1, Nivel 1',
    cantidadTotal: 400,
    cantidadMinAlerta: 80,
    cantidadMaxAlerta: 600,
    precioVenta: 28000,
    precioCompra: 15000,
    categoria: 'Antibióticos',
  },
  {
    nombre: 'Ampicilina + Sulbactam 1.5g Inyectable',
    sku: 'MED-ANT-002',
    codigoBarras: '7702057002002',
    laboratorio: 'PFIZER S.A.S.',
    descripcion: 'Antibiótico betalactámico con inhibidor de betalactamasas',
    principioActivo: 'AMPICILINA + SULBACTAM',
    concentracion: '1g + 500mg',
    formaFarmaceutica: 'POLVO PARA RECONSTITUIR A SOLUCION INYECTABLE',
    unidadMedida: 'g',
    viaAdministracion: 'INTRAVENOSA',
    presentacion: 'Caja por 10 viales + diluyente',
    codigoAtc: 'J01CR01',
    cum: '19950345',
    registroSanitario: 'INVIMA 2022M-0006789-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante B2, Nivel 2',
    cantidadTotal: 200,
    cantidadMinAlerta: 40,
    cantidadMaxAlerta: 300,
    precioVenta: 85000,
    precioCompra: 52000,
    categoria: 'Antibióticos',
  },
  {
    nombre: 'Ciprofloxacino 500mg Tabletas',
    sku: 'MED-ANT-003',
    codigoBarras: '7702057002003',
    laboratorio: 'LABORATORIOS LA SANTE S.A.',
    descripcion: 'Antibiótico fluoroquinolona de amplio espectro',
    principioActivo: 'CIPROFLOXACINO CLORHIDRATO',
    concentracion: '500 mg',
    formaFarmaceutica: 'TABLETA RECUBIERTA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 14 tabletas recubiertas en blíster',
    codigoAtc: 'J01MA02',
    cum: '20020095',
    registroSanitario: 'INVIMA 2016M-0011422-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante B1, Nivel 3',
    cantidadTotal: 250,
    cantidadMinAlerta: 50,
    cantidadMaxAlerta: 400,
    precioVenta: 32000,
    precioCompra: 18000,
    categoria: 'Antibióticos',
  },
  {
    nombre: 'Vancomicina 500mg Inyectable',
    sku: 'MED-ANT-004',
    codigoBarras: '7702057002004',
    laboratorio: 'LABORATORIOS BAXTER S.A.',
    descripcion: 'Antibiótico glucopéptido para infecciones graves por gram positivos',
    principioActivo: 'VANCOMICINA CLORHIDRATO',
    concentracion: '500 mg',
    formaFarmaceutica: 'POLVO LIOFILIZADO PARA RECONSTITUIR A SOLUCION INYECTABLE',
    unidadMedida: 'mg',
    viaAdministracion: 'INTRAVENOSA',
    presentacion: 'Caja por 10 viales de polvo liofilizado',
    codigoAtc: 'J01XA01',
    cum: '20111871',
    registroSanitario: 'INVIMA 2019M-0018709',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante B2, Nivel 1',
    cantidadTotal: 100,
    cantidadMinAlerta: 20,
    cantidadMaxAlerta: 150,
    precioVenta: 125000,
    precioCompra: 78000,
    categoria: 'Antibióticos',
  },
  {
    nombre: 'Vancomicina 1g Inyectable',
    sku: 'MED-ANT-004B',
    codigoBarras: '7702057002004B',
    laboratorio: 'ANTIBIOTICOS DE COLOMBIA S.A.S.',
    descripcion: 'Antibiótico glucopéptido para infecciones graves - presentación hospitalaria',
    principioActivo: 'VANCOMICINA CLORHIDRATO',
    concentracion: '1 g',
    formaFarmaceutica: 'POLVO LIOFILIZADO PARA RECONSTITUIR A SOLUCION INYECTABLE',
    unidadMedida: 'g',
    viaAdministracion: 'INTRAVENOSA',
    presentacion: 'Caja por 10 viales de polvo liofilizado',
    codigoAtc: 'J01XA01',
    cum: '20120231',
    registroSanitario: 'INVIMA 2023M-0018274-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante B2, Nivel 1',
    cantidadTotal: 80,
    cantidadMinAlerta: 15,
    cantidadMaxAlerta: 120,
    precioVenta: 185000,
    precioCompra: 115000,
    categoria: 'Antibióticos',
  },

  // ==================== ANTIHIPERTENSIVOS ====================
  {
    nombre: 'Losartán 50mg Tabletas',
    sku: 'MED-HIP-001',
    codigoBarras: '7702057003001',
    laboratorio: 'MEMPHIS PRODUCTS S.A.',
    descripcion: 'Antagonista de receptores de angiotensina II para hipertensión',
    principioActivo: 'LOSARTAN POTASICO',
    concentracion: '50 mg',
    formaFarmaceutica: 'TABLETA RECUBIERTA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas recubiertas en blíster',
    codigoAtc: 'C09CA01',
    cum: '19965332',
    registroSanitario: 'INVIMA 2017M-0005916-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante C1, Nivel 1',
    cantidadTotal: 350,
    cantidadMinAlerta: 60,
    cantidadMaxAlerta: 500,
    precioVenta: 22000,
    precioCompra: 12000,
    categoria: 'Antihipertensivos',
  },
  {
    nombre: 'Enalapril 20mg Tabletas',
    sku: 'MED-HIP-002',
    codigoBarras: '7702057003002',
    laboratorio: 'TECNOQUIMICAS S.A.',
    descripcion: 'Inhibidor de la ECA para hipertensión e insuficiencia cardíaca',
    principioActivo: 'ENALAPRIL MALEATO',
    concentracion: '20 mg',
    formaFarmaceutica: 'TABLETA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas',
    codigoAtc: 'C09AA02',
    cum: '36123',
    registroSanitario: 'INVIMA 2019M-011527-R3',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante C1, Nivel 2',
    cantidadTotal: 280,
    cantidadMinAlerta: 50,
    cantidadMaxAlerta: 400,
    precioVenta: 18000,
    precioCompra: 9500,
    categoria: 'Antihipertensivos',
  },
  {
    nombre: 'Amlodipino 5mg Tabletas',
    sku: 'MED-HIP-003',
    codigoBarras: '7702057003003',
    laboratorio: 'FARMA DE COLOMBIA S.A.S.',
    descripcion: 'Bloqueador de canales de calcio para hipertensión y angina',
    principioActivo: 'AMLODIPINO BESILATO',
    concentracion: '5 mg',
    formaFarmaceutica: 'TABLETA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas',
    codigoAtc: 'C08CA01',
    cum: '19974781',
    registroSanitario: 'INVIMA 2020M-0007035-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante C1, Nivel 3',
    cantidadTotal: 320,
    cantidadMinAlerta: 60,
    cantidadMaxAlerta: 450,
    precioVenta: 24000,
    precioCompra: 13500,
    categoria: 'Antihipertensivos',
  },
  {
    nombre: 'Amlodipino 10mg Tabletas',
    sku: 'MED-HIP-003B',
    codigoBarras: '7702057003003B',
    laboratorio: 'MERCK S.A.',
    descripcion: 'Bloqueador de canales de calcio - dosis alta',
    principioActivo: 'AMLODIPINO BESILATO',
    concentracion: '10 mg',
    formaFarmaceutica: 'TABLETA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas',
    codigoAtc: 'C08CA01',
    cum: '20040649',
    registroSanitario: 'INVIMA 2023M-0014354-R2',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante C1, Nivel 3',
    cantidadTotal: 200,
    cantidadMinAlerta: 40,
    cantidadMaxAlerta: 300,
    precioVenta: 32000,
    precioCompra: 18500,
    categoria: 'Antihipertensivos',
  },

  // ==================== ANTIDIABÉTICOS ====================
  {
    nombre: 'Metformina 850mg Tabletas',
    sku: 'MED-DIA-001',
    codigoBarras: '7702057004001',
    laboratorio: 'PROCAPS S.A.',
    descripcion: 'Antidiabético oral de primera línea para diabetes tipo 2',
    principioActivo: 'METFORMINA CLORHIDRATO',
    concentracion: '850 mg',
    formaFarmaceutica: 'TABLETA RECUBIERTA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas recubiertas',
    codigoAtc: 'A10BA02',
    cum: '20082257',
    registroSanitario: 'INVIMA 2015M-0015862',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante D1, Nivel 1',
    cantidadTotal: 400,
    cantidadMinAlerta: 80,
    cantidadMaxAlerta: 600,
    precioVenta: 15000,
    precioCompra: 7500,
    categoria: 'Antidiabéticos',
  },
  {
    nombre: 'Metformina 1000mg Tabletas LP',
    sku: 'MED-DIA-001B',
    codigoBarras: '7702057004001B',
    laboratorio: 'LABORATORIOS LEGRAND S.A.',
    descripcion: 'Antidiabético oral de liberación prolongada',
    principioActivo: 'METFORMINA CLORHIDRATO',
    concentracion: '1000 mg',
    formaFarmaceutica: 'TABLETA DE LIBERACION PROLONGADA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas de liberación prolongada',
    codigoAtc: 'A10BA02',
    cum: '20227451',
    registroSanitario: 'INVIMA 2025M-0022013',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante D1, Nivel 1',
    cantidadTotal: 250,
    cantidadMinAlerta: 50,
    cantidadMaxAlerta: 400,
    precioVenta: 28000,
    precioCompra: 16000,
    categoria: 'Antidiabéticos',
  },
  {
    nombre: 'Insulina NPH 100UI/ml',
    sku: 'MED-DIA-002',
    codigoBarras: '7702057004002',
    laboratorio: 'NOVO NORDISK COLOMBIA S.A.S.',
    descripcion: 'Insulina humana de acción intermedia',
    principioActivo: 'INSULINA HUMANA NPH (ISOFANA)',
    concentracion: '100 UI/ml',
    formaFarmaceutica: 'SUSPENSION INYECTABLE',
    unidadMedida: 'UI/ml',
    viaAdministracion: 'SUBCUTANEA',
    presentacion: 'Caja por 1 vial de 10ml',
    codigoAtc: 'A10AC01',
    cum: '19920567',
    registroSanitario: 'INVIMA 2021M-0014567-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Refrigeración (2-8°C)',
    requiereCadenaFrio: true,
    ubicacionAlmacen: 'Refrigerador 1, Nivel 1',
    cantidadTotal: 80,
    cantidadMinAlerta: 15,
    cantidadMaxAlerta: 120,
    precioVenta: 85000,
    precioCompra: 55000,
    categoria: 'Antidiabéticos',
  },
  {
    nombre: 'Insulina Glargina 100UI/ml',
    sku: 'MED-DIA-002B',
    codigoBarras: '7702057004002B',
    laboratorio: 'SANOFI-AVENTIS DE COLOMBIA S.A.',
    descripcion: 'Insulina análoga de acción prolongada (24 horas)',
    principioActivo: 'INSULINA GLARGINA',
    concentracion: '100 UI/ml',
    formaFarmaceutica: 'SOLUCION INYECTABLE',
    unidadMedida: 'UI/ml',
    viaAdministracion: 'SUBCUTANEA',
    presentacion: 'Caja por 5 plumas prellenadas de 3ml (SoloStar)',
    codigoAtc: 'A10AE04',
    cum: '20082413',
    registroSanitario: 'INVIMA 2015M-0016191',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Refrigeración (2-8°C)',
    requiereCadenaFrio: true,
    ubicacionAlmacen: 'Refrigerador 1, Nivel 1',
    cantidadTotal: 50,
    cantidadMinAlerta: 10,
    cantidadMaxAlerta: 80,
    precioVenta: 285000,
    precioCompra: 195000,
    categoria: 'Antidiabéticos',
  },
  {
    nombre: 'Glibenclamida 5mg Tabletas',
    sku: 'MED-DIA-003',
    codigoBarras: '7702057004003',
    laboratorio: 'TECNOQUIMICAS S.A.',
    descripcion: 'Sulfonilurea para diabetes tipo 2',
    principioActivo: 'GLIBENCLAMIDA',
    concentracion: '5 mg',
    formaFarmaceutica: 'TABLETA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas',
    codigoAtc: 'A10BB01',
    cum: '19993255',
    registroSanitario: 'INVIMA 2022M-0009254-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante D1, Nivel 2',
    cantidadTotal: 300,
    cantidadMinAlerta: 60,
    cantidadMaxAlerta: 450,
    precioVenta: 12000,
    precioCompra: 6000,
    categoria: 'Antidiabéticos',
  },

  // ==================== GASTROINTESTINALES ====================
  {
    nombre: 'Omeprazol 40mg Cápsulas',
    sku: 'MED-GAS-001',
    codigoBarras: '7702057005001',
    laboratorio: 'LABORATORIOS BUSSIÉ S.A.',
    descripcion: 'Inhibidor de bomba de protones para úlcera y ERGE',
    principioActivo: 'OMEPRAZOL',
    concentracion: '40 mg',
    formaFarmaceutica: 'CAPSULA DURA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 cápsulas en blíster PVC/Aluminio',
    codigoAtc: 'A02BC01',
    cum: '40026',
    registroSanitario: 'INVIMA 2012M-012793-R2',
    requiereReceta: false,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante E1, Nivel 1',
    cantidadTotal: 450,
    cantidadMinAlerta: 90,
    cantidadMaxAlerta: 700,
    precioVenta: 18000,
    precioCompra: 9000,
    categoria: 'Gastrointestinales',
  },
  {
    nombre: 'Omeprazol 40mg Inyectable',
    sku: 'MED-GAS-001B',
    codigoBarras: '7702057005001B',
    laboratorio: 'HOSPIRA COLOMBIA S.A.S.',
    descripcion: 'IBP inyectable para sangrado digestivo y pacientes NPO',
    principioActivo: 'OMEPRAZOL SODICO',
    concentracion: '40 mg',
    formaFarmaceutica: 'POLVO LIOFILIZADO PARA RECONSTITUIR A SOLUCION INYECTABLE',
    unidadMedida: 'mg',
    viaAdministracion: 'INTRAVENOSA',
    presentacion: 'Caja por 5 viales + diluyente',
    codigoAtc: 'A02BC01',
    cum: '20050234',
    registroSanitario: 'INVIMA 2020M-0015678-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante E2, Nivel 1',
    cantidadTotal: 100,
    cantidadMinAlerta: 20,
    cantidadMaxAlerta: 150,
    precioVenta: 95000,
    precioCompra: 62000,
    categoria: 'Gastrointestinales',
  },
  {
    nombre: 'Metoclopramida 10mg Tabletas',
    sku: 'MED-GAS-002',
    codigoBarras: '7702057005002',
    laboratorio: 'NOVAMED S.A.S.',
    descripcion: 'Antiemético y procinético',
    principioActivo: 'METOCLOPRAMIDA CLORHIDRATO',
    concentracion: '10 mg',
    formaFarmaceutica: 'TABLETA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas',
    codigoAtc: 'A03FA01',
    cum: '20050909',
    registroSanitario: 'INVIMA 2021M-0013901-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante E1, Nivel 2',
    cantidadTotal: 280,
    cantidadMinAlerta: 50,
    cantidadMaxAlerta: 400,
    precioVenta: 8500,
    precioCompra: 4200,
    categoria: 'Gastrointestinales',
  },
  {
    nombre: 'Metoclopramida 10mg/2ml Inyectable',
    sku: 'MED-GAS-002B',
    codigoBarras: '7702057005002B',
    laboratorio: 'VITALIS S.A.C.I.',
    descripcion: 'Antiemético inyectable para náuseas y vómito severo',
    principioActivo: 'METOCLOPRAMIDA CLORHIDRATO',
    concentracion: '10 mg/2ml',
    formaFarmaceutica: 'SOLUCION INYECTABLE',
    unidadMedida: 'mg/ml',
    viaAdministracion: 'INTRAMUSCULAR',
    presentacion: 'Caja por 10 ampollas de 2ml',
    codigoAtc: 'A03FA01',
    cum: '20162259',
    registroSanitario: 'INVIMA 2021M-0020010',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante E2, Nivel 2',
    cantidadTotal: 150,
    cantidadMinAlerta: 30,
    cantidadMaxAlerta: 250,
    precioVenta: 25000,
    precioCompra: 14000,
    categoria: 'Gastrointestinales',
  },

  // ==================== SOLUCIONES IV ====================
  {
    nombre: 'Solución Salina 0.9% x 500ml',
    sku: 'MED-SOL-001',
    codigoBarras: '7702057006001',
    laboratorio: 'LABORATORIOS BAXTER S.A.',
    descripcion: 'Solución isotónica para hidratación y dilución',
    principioActivo: 'CLORURO DE SODIO',
    concentracion: '0.9%',
    formaFarmaceutica: 'SOLUCION PARA INFUSION',
    unidadMedida: '%',
    viaAdministracion: 'INTRAVENOSA',
    presentacion: 'Bolsa x 500ml Viaflex',
    codigoAtc: 'B05BB01',
    cum: '19850001',
    registroSanitario: 'INVIMA 2020M-0008901-R2',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante F1, Nivel 1',
    cantidadTotal: 500,
    cantidadMinAlerta: 100,
    cantidadMaxAlerta: 800,
    precioVenta: 6500,
    precioCompra: 3200,
    categoria: 'Soluciones IV',
  },
  {
    nombre: 'Solución Salina 0.9% x 1000ml',
    sku: 'MED-SOL-001B',
    codigoBarras: '7702057006001B',
    laboratorio: 'LABORATORIOS BAXTER S.A.',
    descripcion: 'Solución isotónica para hidratación - presentación grande',
    principioActivo: 'CLORURO DE SODIO',
    concentracion: '0.9%',
    formaFarmaceutica: 'SOLUCION PARA INFUSION',
    unidadMedida: '%',
    viaAdministracion: 'INTRAVENOSA',
    presentacion: 'Bolsa x 1000ml Viaflex',
    codigoAtc: 'B05BB01',
    cum: '19850002',
    registroSanitario: 'INVIMA 2020M-0008902-R2',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante F1, Nivel 1',
    cantidadTotal: 400,
    cantidadMinAlerta: 80,
    cantidadMaxAlerta: 600,
    precioVenta: 9500,
    precioCompra: 4800,
    categoria: 'Soluciones IV',
  },
  {
    nombre: 'Dextrosa 5% en AD x 500ml',
    sku: 'MED-SOL-002',
    codigoBarras: '7702057006002',
    laboratorio: 'LABORATORIOS BAXTER S.A.',
    descripcion: 'Solución glucosada para aporte calórico e hidratación',
    principioActivo: 'DEXTROSA',
    concentracion: '5%',
    formaFarmaceutica: 'SOLUCION PARA INFUSION',
    unidadMedida: '%',
    viaAdministracion: 'INTRAVENOSA',
    presentacion: 'Bolsa x 500ml Viaflex',
    codigoAtc: 'B05BA03',
    cum: '19860034',
    registroSanitario: 'INVIMA 2021M-0009012-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante F1, Nivel 2',
    cantidadTotal: 350,
    cantidadMinAlerta: 70,
    cantidadMaxAlerta: 500,
    precioVenta: 7200,
    precioCompra: 3600,
    categoria: 'Soluciones IV',
  },
  {
    nombre: 'Lactato de Ringer x 500ml',
    sku: 'MED-SOL-003',
    codigoBarras: '7702057006003',
    laboratorio: 'LABORATORIOS BAXTER S.A.',
    descripcion: 'Solución electrolítica balanceada tipo Hartmann',
    principioActivo: 'LACTATO DE RINGER',
    concentracion: 'Compuesto',
    formaFarmaceutica: 'SOLUCION PARA INFUSION',
    unidadMedida: 'mEq/L',
    viaAdministracion: 'INTRAVENOSA',
    presentacion: 'Bolsa x 500ml Viaflex',
    codigoAtc: 'B05BB01',
    cum: '19870056',
    registroSanitario: 'INVIMA 2022M-0010123-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante F1, Nivel 3',
    cantidadTotal: 300,
    cantidadMinAlerta: 60,
    cantidadMaxAlerta: 450,
    precioVenta: 8500,
    precioCompra: 4200,
    categoria: 'Soluciones IV',
  },

  // ==================== RESPIRATORIOS ====================
  {
    nombre: 'Salbutamol Inhalador 100mcg',
    sku: 'MED-RES-001',
    codigoBarras: '7702057007001',
    laboratorio: 'GLAXOSMITHKLINE COLOMBIA S.A.',
    descripcion: 'Broncodilatador beta-2 agonista de acción corta (SABA)',
    principioActivo: 'SALBUTAMOL SULFATO',
    concentracion: '100 mcg/dosis',
    formaFarmaceutica: 'AEROSOL PARA INHALACION',
    unidadMedida: 'mcg/dosis',
    viaAdministracion: 'INHALACION',
    presentacion: 'Inhalador x 200 dosis',
    codigoAtc: 'R03AC02',
    cum: '19994006',
    registroSanitario: 'INVIMA 2019M-0009124-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante G1, Nivel 1',
    cantidadTotal: 150,
    cantidadMinAlerta: 30,
    cantidadMaxAlerta: 250,
    precioVenta: 35000,
    precioCompra: 22000,
    categoria: 'Respiratorios',
  },
  {
    nombre: 'Salbutamol Solución para Nebulizar',
    sku: 'MED-RES-001B',
    codigoBarras: '7702057007001B',
    laboratorio: 'NOVAMED S.A.S.',
    descripcion: 'Broncodilatador para nebulización',
    principioActivo: 'SALBUTAMOL SULFATO',
    concentracion: '5 mg/ml',
    formaFarmaceutica: 'SOLUCION PARA NEBULIZACION',
    unidadMedida: 'mg/ml',
    viaAdministracion: 'INHALACION',
    presentacion: 'Frasco x 20ml',
    codigoAtc: 'R03AC02',
    cum: '19988817',
    registroSanitario: 'INVIMA 2021M-0008248-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante G1, Nivel 1',
    cantidadTotal: 100,
    cantidadMinAlerta: 20,
    cantidadMaxAlerta: 150,
    precioVenta: 28000,
    precioCompra: 16000,
    categoria: 'Respiratorios',
  },
  {
    nombre: 'Beclometasona Inhalador 250mcg',
    sku: 'MED-RES-002',
    codigoBarras: '7702057007002',
    laboratorio: 'FAES FARMA CHILE LTDA.',
    descripcion: 'Corticoide inhalado para control del asma',
    principioActivo: 'BECLOMETASONA DIPROPIONATO',
    concentracion: '250 mcg/dosis',
    formaFarmaceutica: 'SOLUCION PARA INHALACION',
    unidadMedida: 'mcg/dosis',
    viaAdministracion: 'INHALACION',
    presentacion: 'Inhalador x 200 dosis',
    codigoAtc: 'R03BA01',
    cum: '20011750',
    registroSanitario: 'INVIMA 2020M-0010524-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante G1, Nivel 2',
    cantidadTotal: 100,
    cantidadMinAlerta: 20,
    cantidadMaxAlerta: 150,
    precioVenta: 65000,
    precioCompra: 42000,
    categoria: 'Respiratorios',
  },

  // ==================== PSICOTRÓPICOS ====================
  {
    nombre: 'Diazepam 10mg/2ml Inyectable',
    sku: 'MED-PSI-001',
    codigoBarras: '7702057008001',
    laboratorio: 'LABORATORIO BIOSANO S.A.',
    descripcion: 'Benzodiacepina para ansiedad, convulsiones y sedación',
    principioActivo: 'DIAZEPAM',
    concentracion: '10 mg/2ml',
    formaFarmaceutica: 'SOLUCION INYECTABLE',
    unidadMedida: 'mg/ml',
    viaAdministracion: 'INTRAVENOSA',
    presentacion: 'Caja por 10 ampollas de 2ml',
    codigoAtc: 'N05BA01',
    cum: '20019151',
    registroSanitario: 'INVIMA 2023M-0011621-R2',
    requiereReceta: true,
    controlado: true,
    tipoControlado: 'IV',
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante Controlados, Nivel 2',
    cantidadTotal: 80,
    cantidadMinAlerta: 15,
    cantidadMaxAlerta: 120,
    precioVenta: 55000,
    precioCompra: 35000,
    categoria: 'Psicotrópicos',
  },
  {
    nombre: 'Diazepam 5mg Tabletas',
    sku: 'MED-PSI-001B',
    codigoBarras: '7702057008001B',
    laboratorio: 'GENFAR S.A.',
    descripcion: 'Benzodiacepina oral para ansiedad e insomnio',
    principioActivo: 'DIAZEPAM',
    concentracion: '5 mg',
    formaFarmaceutica: 'TABLETA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas',
    codigoAtc: 'N05BA01',
    cum: '19920345',
    registroSanitario: 'INVIMA 2020M-0012345-R2',
    requiereReceta: true,
    controlado: true,
    tipoControlado: 'IV',
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante Controlados, Nivel 2',
    cantidadTotal: 100,
    cantidadMinAlerta: 20,
    cantidadMaxAlerta: 150,
    precioVenta: 18000,
    precioCompra: 9500,
    categoria: 'Psicotrópicos',
  },
  {
    nombre: 'Haloperidol 5mg/ml Inyectable',
    sku: 'MED-PSI-002',
    codigoBarras: '7702057008002',
    laboratorio: 'LABORATORIOS RYAN DE COLOMBIA S.A.S.',
    descripcion: 'Antipsicótico típico para agitación y psicosis',
    principioActivo: 'HALOPERIDOL',
    concentracion: '5 mg/ml',
    formaFarmaceutica: 'SOLUCION INYECTABLE',
    unidadMedida: 'mg/ml',
    viaAdministracion: 'INTRAMUSCULAR',
    presentacion: 'Caja por 5 ampollas de 1ml',
    codigoAtc: 'N05AD01',
    cum: '20004992',
    registroSanitario: 'INVIMA 2019M-0010081-R1',
    requiereReceta: true,
    controlado: true,
    tipoControlado: 'III',
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante Controlados, Nivel 3',
    cantidadTotal: 60,
    cantidadMinAlerta: 10,
    cantidadMaxAlerta: 100,
    precioVenta: 42000,
    precioCompra: 26000,
    categoria: 'Psicotrópicos',
  },
  {
    nombre: 'Haloperidol 5mg Tabletas',
    sku: 'MED-PSI-002B',
    codigoBarras: '7702057008002B',
    laboratorio: 'LABORATORIOS SIEGFRIED S.A.S.',
    descripcion: 'Antipsicótico típico oral',
    principioActivo: 'HALOPERIDOL',
    concentracion: '5 mg',
    formaFarmaceutica: 'TABLETA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 20 tabletas',
    codigoAtc: 'N05AD01',
    cum: '45922',
    registroSanitario: 'INVIMA 2020M-013948-R3',
    requiereReceta: true,
    controlado: true,
    tipoControlado: 'III',
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante Controlados, Nivel 3',
    cantidadTotal: 80,
    cantidadMinAlerta: 15,
    cantidadMaxAlerta: 120,
    precioVenta: 25000,
    precioCompra: 14000,
    categoria: 'Psicotrópicos',
  },

  // ==================== CARDIOVASCULARES ====================
  {
    nombre: 'Atorvastatina 20mg Tabletas',
    sku: 'MED-CAR-001',
    codigoBarras: '7702057009001',
    laboratorio: 'LABORATORIOS ECAR S.A.',
    descripcion: 'Estatina para reducción de colesterol LDL',
    principioActivo: 'ATORVASTATINA CALCICA',
    concentracion: '20 mg',
    formaFarmaceutica: 'TABLETA RECUBIERTA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas recubiertas',
    codigoAtc: 'C10AA05',
    cum: '19963352',
    registroSanitario: 'INVIMA 2022M-0005892-R2',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante C2, Nivel 1',
    cantidadTotal: 350,
    cantidadMinAlerta: 70,
    cantidadMaxAlerta: 500,
    precioVenta: 32000,
    precioCompra: 18000,
    categoria: 'Cardiovasculares',
  },
  {
    nombre: 'Atorvastatina 40mg Tabletas',
    sku: 'MED-CAR-001B',
    codigoBarras: '7702057009001B',
    laboratorio: 'LABORATORIOS ECAR S.A.',
    descripcion: 'Estatina de alta intensidad para dislipidemia',
    principioActivo: 'ATORVASTATINA CALCICA',
    concentracion: '40 mg',
    formaFarmaceutica: 'TABLETA RECUBIERTA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas recubiertas',
    codigoAtc: 'C10AA05',
    cum: '20085383',
    registroSanitario: 'INVIMA 2022M-0016377-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante C2, Nivel 1',
    cantidadTotal: 250,
    cantidadMinAlerta: 50,
    cantidadMaxAlerta: 400,
    precioVenta: 45000,
    precioCompra: 26000,
    categoria: 'Cardiovasculares',
  },
  {
    nombre: 'Furosemida 40mg Tabletas',
    sku: 'MED-CAR-002',
    codigoBarras: '7702057009002',
    laboratorio: 'SANOFI-AVENTIS DE COLOMBIA S.A.',
    descripcion: 'Diurético de asa para edema e insuficiencia cardíaca',
    principioActivo: 'FUROSEMIDA',
    concentracion: '40 mg',
    formaFarmaceutica: 'TABLETA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 20 tabletas',
    codigoAtc: 'C03CA01',
    cum: '19880567',
    registroSanitario: 'INVIMA 2021M-0011234-R2',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante C2, Nivel 2',
    cantidadTotal: 300,
    cantidadMinAlerta: 60,
    cantidadMaxAlerta: 450,
    precioVenta: 12000,
    precioCompra: 6000,
    categoria: 'Cardiovasculares',
  },
  {
    nombre: 'Furosemida 20mg/2ml Inyectable',
    sku: 'MED-CAR-002B',
    codigoBarras: '7702057009002B',
    laboratorio: 'HOSPIRA COLOMBIA S.A.S.',
    descripcion: 'Diurético de asa inyectable para edema agudo',
    principioActivo: 'FUROSEMIDA',
    concentracion: '20 mg/2ml',
    formaFarmaceutica: 'SOLUCION INYECTABLE',
    unidadMedida: 'mg/ml',
    viaAdministracion: 'INTRAVENOSA',
    presentacion: 'Caja por 5 ampollas de 2ml',
    codigoAtc: 'C03CA01',
    cum: '19900678',
    registroSanitario: 'INVIMA 2020M-0012345-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante C2, Nivel 3',
    cantidadTotal: 150,
    cantidadMinAlerta: 30,
    cantidadMaxAlerta: 250,
    precioVenta: 35000,
    precioCompra: 20000,
    categoria: 'Cardiovasculares',
  },

  // ==================== ANTICOAGULANTES ====================
  {
    nombre: 'Enoxaparina 40mg Jeringa',
    sku: 'MED-ACO-001',
    codigoBarras: '7702057010001',
    laboratorio: 'SANOFI-AVENTIS DE COLOMBIA S.A.',
    descripcion: 'Heparina de bajo peso molecular para profilaxis TVP',
    principioActivo: 'ENOXAPARINA SODICA',
    concentracion: '40 mg/0.4ml',
    formaFarmaceutica: 'SOLUCION INYECTABLE EN JERINGA PRELLENADA',
    unidadMedida: 'mg',
    viaAdministracion: 'SUBCUTANEA',
    presentacion: 'Caja por 2 jeringas prellenadas de 0.4ml',
    codigoAtc: 'B01AB05',
    cum: '19950789',
    registroSanitario: 'INVIMA 2021M-0013456-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante H1, Nivel 1',
    cantidadTotal: 200,
    cantidadMinAlerta: 40,
    cantidadMaxAlerta: 300,
    precioVenta: 85000,
    precioCompra: 55000,
    categoria: 'Anticoagulantes',
  },
  {
    nombre: 'Enoxaparina 60mg Jeringa',
    sku: 'MED-ACO-001B',
    codigoBarras: '7702057010001B',
    laboratorio: 'SANOFI-AVENTIS DE COLOMBIA S.A.',
    descripcion: 'Heparina de bajo peso molecular dosis terapéutica',
    principioActivo: 'ENOXAPARINA SODICA',
    concentracion: '60 mg/0.6ml',
    formaFarmaceutica: 'SOLUCION INYECTABLE EN JERINGA PRELLENADA',
    unidadMedida: 'mg',
    viaAdministracion: 'SUBCUTANEA',
    presentacion: 'Caja por 2 jeringas prellenadas de 0.6ml',
    codigoAtc: 'B01AB05',
    cum: '19960890',
    registroSanitario: 'INVIMA 2021M-0013457-R1',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante H1, Nivel 1',
    cantidadTotal: 150,
    cantidadMinAlerta: 30,
    cantidadMaxAlerta: 250,
    precioVenta: 125000,
    precioCompra: 82000,
    categoria: 'Anticoagulantes',
  },
  {
    nombre: 'Warfarina 5mg Tabletas',
    sku: 'MED-ACO-002',
    codigoBarras: '7702057010002',
    laboratorio: 'TECNOQUIMICAS S.A.',
    descripcion: 'Anticoagulante oral antagonista de vitamina K',
    principioActivo: 'WARFARINA SODICA',
    concentracion: '5 mg',
    formaFarmaceutica: 'TABLETA',
    unidadMedida: 'mg',
    viaAdministracion: 'ORAL',
    presentacion: 'Caja por 30 tabletas',
    codigoAtc: 'B01AA03',
    cum: '19880901',
    registroSanitario: 'INVIMA 2020M-0014567-R2',
    requiereReceta: true,
    controlado: false,
    tipoControlado: null,
    temperaturaAlmacenamiento: 'Temperatura ambiente (15-30°C)',
    requiereCadenaFrio: false,
    ubicacionAlmacen: 'Estante H1, Nivel 2',
    cantidadTotal: 250,
    cantidadMinAlerta: 50,
    cantidadMaxAlerta: 400,
    precioVenta: 22000,
    precioCompra: 12000,
    categoria: 'Anticoagulantes',
  },
];

async function seedProductosFarmacia() {
  console.log('Iniciando seed de productos farmacéuticos con datos INVIMA...');
  console.log('Fuente: datos.gov.co - CUM INVIMA Colombia\n');

  try {
    // 1. Crear categorías
    console.log('Creando categorías de productos...');
    const categoriasMap = {};

    for (const cat of categorias) {
      // Buscar si existe la categoría por nombre
      let categoria = await prisma.categoriaProducto.findFirst({
        where: { nombre: cat.nombre },
      });

      if (categoria) {
        // Actualizar si existe
        categoria = await prisma.categoriaProducto.update({
          where: { id: categoria.id },
          data: { descripcion: cat.descripcion, color: cat.color },
        });
        console.log(`  ↺ Categoría actualizada: ${cat.nombre}`);
      } else {
        // Crear si no existe
        categoria = await prisma.categoriaProducto.create({
          data: cat,
        });
        console.log(`  ✓ Categoría creada: ${cat.nombre}`);
      }
      categoriasMap[cat.nombre] = categoria.id;
    }

    // 2. Crear productos
    console.log('\nCreando productos farmacéuticos...');
    let created = 0;
    let updated = 0;

    for (const prod of productos) {
      const { categoria, ...productoData } = prod;
      productoData.categoriaId = categoriasMap[categoria];

      try {
        const existing = await prisma.producto.findUnique({
          where: { sku: productoData.sku },
        });

        if (existing) {
          await prisma.producto.update({
            where: { id: existing.id },
            data: productoData,
          });
          updated++;
          console.log(`  ↺ Actualizado: ${prod.nombre}`);
        } else {
          await prisma.producto.create({
            data: productoData,
          });
          created++;
          console.log(`  ✓ Creado: ${prod.nombre}`);
        }
      } catch (err) {
        console.error(`  ✗ Error con ${prod.nombre}:`, err.message);
      }
    }

    console.log('\n========================================');
    console.log('Seed completado:');
    console.log(`  - Categorías: ${Object.keys(categoriasMap).length}`);
    console.log(`  - Productos creados: ${created}`);
    console.log(`  - Productos actualizados: ${updated}`);
    console.log('========================================');

  } catch (error) {
    console.error('Error en seed:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seedProductosFarmacia();
